<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FixtureEnumType.proto

namespace GPBMetadata;

class FixtureEnumType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA5\x01\x0A\x15FixtureEnumType.proto\x12\x14DATA_MANAGER_FIXTURE*T\x0A\x0CFixtureState\x12\x15\x0A\x11FixtureState_NONE\x10\x00\x12\x17\x0A\x13FixtureState_ACTIVE\x10\x01\x12\x14\x0A\x10FixtureState_MAX\x10\x02B\x18Z\x16./DATA_MANAGER_FIXTUREb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

