import * as fs from 'fs'
import * as path from 'path'
import type { ProtoMessage, ProtoEnum, CodeGenLanguage } from '../../shared/types'

// ── Strategy 인터페이스 ──────────────────────────────────────

export interface ICodeGenerator {
  readonly language: CodeGenLanguage
  generate(messages: ProtoMessage[], enums: ProtoEnum[], outputDir: string): void
}

// ── C++ 코드 생성기 ──────────────────────────────────────────

export class CppCodeGenerator implements ICodeGenerator {
  readonly language: CodeGenLanguage = 'cpp'

  generate(messages: ProtoMessage[], enums: ProtoEnum[], outputDir: string): void {
    fs.mkdirSync(outputDir, { recursive: true })

    const lines: string[] = []
    lines.push('#pragma once')
    lines.push('#include <string>')
    lines.push('#include <vector>')
    lines.push('')
    lines.push('namespace DATA_TABLE {')
    lines.push('')

    // Enums
    for (const e of enums) {
      lines.push(`  enum class ${e.name} {`)
      for (const v of e.values) {
        lines.push(`    ${v.name} = ${v.number},`)
      }
      lines.push(`  };`)
      lines.push('')
    }

    // Structs
    for (const msg of messages) {
      lines.push(`  struct ${msg.name} {`)
      for (const f of msg.fields) {
        const cppType = this.toCppType(f.type)
        const repeated = f.isRepeated ? `std::vector<${cppType}>` : cppType
        lines.push(`    ${repeated} ${f.name}{};`)
      }
      lines.push(`  };`)
      lines.push('')
    }

    lines.push('} // namespace DATA_TABLE')

    const outPath = path.join(outputDir, 'DataTable.generated.h')
    fs.writeFileSync(outPath, lines.join('\n'), 'utf-8')
  }

  private toCppType(protoType: string): string {
    const map: Record<string, string> = {
      double: 'double',
      float: 'float',
      int32: 'int32_t',
      int64: 'int64_t',
      uint32: 'uint32_t',
      uint64: 'uint64_t',
      sint32: 'int32_t',
      sint64: 'int64_t',
      fixed32: 'uint32_t',
      fixed64: 'uint64_t',
      sfixed32: 'int32_t',
      sfixed64: 'int64_t',
      bool: 'bool',
      string: 'std::string',
      bytes: 'std::string'
    }
    return map[protoType] ?? protoType
  }
}

// ── C# 코드 생성기 ──────────────────────────────────────────

export class CSharpCodeGenerator implements ICodeGenerator {
  readonly language: CodeGenLanguage = 'csharp'

  generate(messages: ProtoMessage[], enums: ProtoEnum[], outputDir: string): void {
    fs.mkdirSync(outputDir, { recursive: true })

    const lines: string[] = []
    lines.push('// <auto-generated />')
    lines.push('using System.Collections.Generic;')
    lines.push('')
    lines.push('namespace DataTable')
    lines.push('{')

    // Enums
    for (const e of enums) {
      lines.push(`  public enum ${e.name}`)
      lines.push(`  {`)
      for (const v of e.values) {
        lines.push(`    ${v.name} = ${v.number},`)
      }
      lines.push(`  }`)
      lines.push('')
    }

    // Classes
    for (const msg of messages) {
      lines.push(`  public class ${msg.name}`)
      lines.push(`  {`)
      for (const f of msg.fields) {
        const csType = this.toCSharpType(f.type)
        const propType = f.isRepeated ? `List<${csType}>` : csType
        const defaultVal = f.isRepeated ? ` = new()` : ''
        lines.push(`    public ${propType} ${this.toPascalCase(f.name)} { get; set; }${defaultVal};`)
      }
      lines.push(`  }`)
      lines.push('')
    }

    lines.push('}')

    const outPath = path.join(outputDir, 'DataTable.generated.cs')
    fs.writeFileSync(outPath, lines.join('\n'), 'utf-8')
  }

  private toCSharpType(protoType: string): string {
    const map: Record<string, string> = {
      double: 'double',
      float: 'float',
      int32: 'int',
      int64: 'long',
      uint32: 'uint',
      uint64: 'ulong',
      sint32: 'int',
      sint64: 'long',
      fixed32: 'uint',
      fixed64: 'ulong',
      sfixed32: 'int',
      sfixed64: 'long',
      bool: 'bool',
      string: 'string',
      bytes: 'byte[]'
    }
    return map[protoType] ?? protoType
  }

  private toPascalCase(name: string): string {
    return name.charAt(0).toUpperCase() + name.slice(1)
  }
}

// ── 레지스트리 ────────────────────────────────────────────────

export class CodeGeneratorService {
  private generators = new Map<CodeGenLanguage, ICodeGenerator>([
    ['cpp', new CppCodeGenerator()],
    ['csharp', new CSharpCodeGenerator()]
  ])

  registerGenerator(generator: ICodeGenerator): void {
    this.generators.set(generator.language, generator)
  }

  generate(
    language: string,
    messages: ProtoMessage[],
    enums: ProtoEnum[],
    outputDir: string
  ): void {
    const generator = this.generators.get(language as CodeGenLanguage)
    if (!generator) throw new Error(`지원하지 않는 언어: ${language}`)
    generator.generate(messages, enums, outputDir)
  }

  getSupportedLanguages(): string[] {
    return Array.from(this.generators.keys())
  }
}

export const codeGeneratorService = new CodeGeneratorService()
