import * as fs from 'fs'
import * as path from 'path'
import type { ParsedProto, ProtoMessage, ProtoEnum, ProtoField } from '../../shared/types'

// proto 기본 타입 → Unreal C++ 타입
const PRIMITIVE_MAP: Record<string, string> = {
  string: 'FString',
  int32: 'int32',
  int64: 'int64',
  uint32: 'uint32',
  uint64: 'uint64',
  sint32: 'int32',
  sint64: 'int64',
  fixed32: 'uint32',
  fixed64: 'uint64',
  float: 'float',
  double: 'double',
  bool: 'bool',
  bytes: 'TArray<uint8>'
}

// Unreal 타입 기본값
const DEFAULT_MAP: Record<string, string> = {
  FString: 'TEXT("")',
  int32: '0',
  int64: '0',
  uint32: '0',
  uint64: '0',
  float: '0.0f',
  double: '0.0',
  bool: 'false'
}

function resolveUnrealType(
  field: ProtoField,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string {
  const isEnum = allEnums.some((e) => e.name === field.type)
  const isMsg = allMessages.some((m) => m.name === field.type)
  let base: string
  if (isEnum) base = `E${field.type}`
  else if (isMsg) base = `F${field.type}`
  else base = PRIMITIVE_MAP[field.type] ?? 'int32'
  return field.isRepeated ? `TArray<${base}>` : base
}

function resolveDefault(
  field: ProtoField,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string {
  if (field.isRepeated) return ''
  if (allEnums.some((e) => e.name === field.type)) return `static_cast<E${field.type}>(0)`
  if (allMessages.some((m) => m.name === field.type)) return ''
  const utype = PRIMITIVE_MAP[field.type]
  if (!utype) return ''
  return DEFAULT_MAP[utype] ?? '0'
}

function generateEnum(e: ProtoEnum): string {
  const maxValue = e.values.reduce((m, v) => Math.max(m, v.number), 0)
  const underlyingType = maxValue > 255 ? 'uint32' : 'uint8'
  const lines: string[] = []
  lines.push(`UENUM(BlueprintType)`)
  lines.push(`enum class E${e.name} : ${underlyingType}`)
  lines.push(`{`)
  for (const v of e.values) {
    lines.push(`    ${e.name}_${v.name} = ${v.number} UMETA(DisplayName = "${v.name}"),`)
  }
  lines.push(`};`)
  return lines.join('\n')
}

function generateStruct(
  msg: ProtoMessage,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string {
  const lines: string[] = []
  lines.push(`USTRUCT(BlueprintType)`)
  lines.push(`struct F${msg.name} : public FTableRowBase`)
  lines.push(`{`)
  lines.push(`    GENERATED_BODY()`)
  for (const field of msg.fields) {
    const utype = resolveUnrealType(field, allEnums, allMessages)
    const def = resolveDefault(field, allEnums, allMessages)
    const defStr = def ? ` = ${def}` : ''
    lines.push(``)
    lines.push(`    UPROPERTY(EditAnywhere, BlueprintReadWrite)`)
    lines.push(`    ${utype} ${field.name}${defStr};`)
  }
  lines.push(`};`)
  return lines.join('\n')
}

export class UnrealCodeGeneratorService {
  /**
   * ParsedProto 를 기반으로 언리얼 C++ 헤더 파일을 생성합니다.
   * - Enum: 원본 proto 파일별로 개별 헤더 생성 (예: MonsterTable.h)
   * - Message: 모든 테이블을 단일 DataTables.h 에 통합
   * @returns 생성된 파일 이름 목록
   */
  generate(parsed: ParsedProto, outputDir: string): string[] {
    fs.mkdirSync(outputDir, { recursive: true })

    const allMessages = parsed.messages
    const allEnums = parsed.enums
    const generatedFiles: string[] = []

    // ── 1. Enum: 소스 파일별 개별 헤더 ──
    const enumsByFile = new Map<string, ProtoEnum[]>()
    for (const e of allEnums) {
      if (!enumsByFile.has(e.sourceFile)) enumsByFile.set(e.sourceFile, [])
      enumsByFile.get(e.sourceFile)!.push(e)
    }
    for (const [sourceFile, enums] of enumsByFile) {
      const baseName = path.basename(sourceFile, '.proto')
      const outFileName = `${baseName}.h`
      const parts: string[] = []
      parts.push(`// Auto-generated by DataManager. DO NOT EDIT.`)
      parts.push(`#pragma once`)
      parts.push(``)
      parts.push(`#include "CoreMinimal.h"`)
      parts.push(`#include "${baseName}.generated.h"`)
      for (const e of enums) {
        parts.push(``)
        parts.push(generateEnum(e))
      }
      parts.push(``)
      fs.writeFileSync(path.join(outputDir, outFileName), parts.join('\n'), 'utf8')
      generatedFiles.push(outFileName)
    }

    // ── 2. Message: 단일 DataTables.h ──
    if (allMessages.length > 0) {
      const outFileName = 'DataTables.h'

      // Enum이 참조되는 파일 → #include 수집
      const enumIncludes = new Set<string>()
      for (const msg of allMessages) {
        for (const field of msg.fields) {
          const refEnum = allEnums.find((e) => e.name === field.type)
          if (refEnum) enumIncludes.add(path.basename(refEnum.sourceFile, '.proto') + '.h')
        }
      }

      const parts: string[] = []
      parts.push(`// Auto-generated by DataManager. DO NOT EDIT.`)
      parts.push(`#pragma once`)
      parts.push(``)
      parts.push(`#include "CoreMinimal.h"`)
      parts.push(`#include "Engine/DataTable.h"`)
      for (const inc of [...enumIncludes].sort()) parts.push(`#include "${inc}"`)
      parts.push(`#include "DataTables.generated.h"`)
      for (const msg of allMessages) {
        parts.push(``)
        parts.push(generateStruct(msg, allEnums, allMessages))
      }
      parts.push(``)
      fs.writeFileSync(path.join(outputDir, outFileName), parts.join('\n'), 'utf8')
      generatedFiles.push(outFileName)
    }

    return generatedFiles
  }
}

export const unrealCodeGenerator = new UnrealCodeGeneratorService()
