import * as fs from 'fs'
import * as path from 'path'
import type { ParsedProto, ProtoMessage, ProtoEnum, ProtoField } from '../../shared/types'

// proto 기본 타입 → Unreal C++ 타입
const PRIMITIVE_MAP: Record<string, string> = {
  string: 'FString',
  int32: 'int32',
  int64: 'int64',
  uint32: 'uint32',
  uint64: 'uint64',
  sint32: 'int32',
  sint64: 'int64',
  fixed32: 'uint32',
  fixed64: 'uint64',
  float: 'float',
  double: 'double',
  bool: 'bool',
  bytes: 'TArray<uint8>'
}

// Unreal 타입 기본값
const DEFAULT_MAP: Record<string, string> = {
  FString: 'TEXT("")',
  int32: '0',
  int64: '0',
  uint32: '0',
  uint64: '0',
  float: '0.0f',
  double: '0.0',
  bool: 'false'
}

function resolveUnrealType(
  field: ProtoField,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string {
  const isEnum = allEnums.some((e) => e.name === field.type)
  const isMsg = allMessages.some((m) => m.name === field.type)
  let base: string
  if (isEnum) base = `E${field.type}`
  else if (isMsg) base = `F${field.type}`
  else base = PRIMITIVE_MAP[field.type] ?? 'int32'
  return field.isRepeated ? `TArray<${base}>` : base
}

function resolveDefault(
  field: ProtoField,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string {
  if (field.isRepeated) return ''
  if (allEnums.some((e) => e.name === field.type)) return `static_cast<E${field.type}>(0)`
  if (allMessages.some((m) => m.name === field.type)) return ''
  const utype = PRIMITIVE_MAP[field.type]
  if (!utype) return ''
  return DEFAULT_MAP[utype] ?? '0'
}

function generateEnum(e: ProtoEnum): string {
  const maxValue = e.values.reduce((m, v) => Math.max(m, v.number), 0)
  const underlyingType = maxValue > 255 ? 'uint32' : 'uint8'
  const lines: string[] = []
  lines.push(`UENUM(BlueprintType)`)
  lines.push(`enum class E${e.name} : ${underlyingType}`)
  lines.push(`{`)
  for (const v of e.values) {
    lines.push(`    ${e.name}_${v.name} = ${v.number} UMETA(DisplayName = "${v.name}"),`)
  }
  lines.push(`};`)
  return lines.join('\n')
}

function generateStruct(
  msg: ProtoMessage,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string {
  const lines: string[] = []
  lines.push(`USTRUCT(BlueprintType)`)
  lines.push(`struct F${msg.name} : public FTableRowBase`)
  lines.push(`{`)
  lines.push(`    GENERATED_BODY()`)
  for (const field of msg.fields) {
    const utype = resolveUnrealType(field, allEnums, allMessages)
    const def = resolveDefault(field, allEnums, allMessages)
    const defStr = def ? ` = ${def}` : ''
    lines.push(``)
    lines.push(`    UPROPERTY(EditAnywhere, BlueprintReadWrite)`)
    lines.push(`    ${utype} ${field.name}${defStr};`)
  }
  lines.push(``)
  lines.push(`    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);`)
  lines.push(`};`)
  return lines.join('\n')
}

export class UnrealCodeGeneratorService {
  /**
   * ParsedProto 를 기반으로 언리얼 C++ 헤더 파일을 생성합니다.
   * - Enum: 원본 proto 파일별로 개별 헤더 생성 (예: MonsterTable.h)
   * - Message: 모든 테이블을 단일 DataTables.h 에 통합
   * @returns 생성된 파일 이름 목록
   */
  generate(parsed: ParsedProto, outputDir: string): string[] {
    fs.mkdirSync(outputDir, { recursive: true })

    const allMessages = parsed.messages
    const allEnums = parsed.enums
    const generatedFiles: string[] = []

    // ── 1. Enum: 소스 파일별 개별 헤더 ──
    const enumsByFile = new Map<string, ProtoEnum[]>()
    for (const e of allEnums) {
      if (!enumsByFile.has(e.sourceFile)) enumsByFile.set(e.sourceFile, [])
      enumsByFile.get(e.sourceFile)!.push(e)
    }
    for (const [sourceFile, enums] of enumsByFile) {
      const baseName = path.basename(sourceFile, '.proto')
      const outFileName = `${baseName}.h`
      const parts: string[] = []
      parts.push(`// Auto-generated by DataManager. DO NOT EDIT.`)
      parts.push(`#pragma once`)
      parts.push(``)
      parts.push(`#include "CoreMinimal.h"`)
      parts.push(`#include "${baseName}.generated.h"`)
      for (const e of enums) {
        parts.push(``)
        parts.push(generateEnum(e))
      }
      parts.push(``)
      fs.writeFileSync(path.join(outputDir, outFileName), parts.join('\n'), 'utf8')
      generatedFiles.push(outFileName)
    }

    // ── 2. Message: 단일 DataTables.h ──
    if (allMessages.length > 0) {
      const outFileName = 'DataTables.h'

      // Enum이 참조되는 파일 → #include 수집
      const enumIncludes = new Set<string>()
      for (const msg of allMessages) {
        for (const field of msg.fields) {
          const refEnum = allEnums.find((e) => e.name === field.type)
          if (refEnum) enumIncludes.add(path.basename(refEnum.sourceFile, '.proto') + '.h')
        }
      }

      const parts: string[] = []
      parts.push(`// Auto-generated by DataManager. DO NOT EDIT.`)
      parts.push(`#pragma once`)
      parts.push(``)
      parts.push(`#include "CoreMinimal.h"`)
      parts.push(`#include "Engine/DataTable.h"`)
      for (const inc of [...enumIncludes].sort()) parts.push(`#include "${inc}"`)
      parts.push(`#include "DataTables.generated.h"`)
      for (const msg of allMessages) {
        parts.push(``)
        parts.push(generateStruct(msg, allEnums, allMessages))
      }
      parts.push(``)
      fs.writeFileSync(path.join(outputDir, outFileName), parts.join('\n'), 'utf8')
      generatedFiles.push(outFileName)
    }

    // ── 3. JSON 로더: DataTableLoader.h / DataTableLoader.cpp ──
    if (allMessages.length > 0) {
      const headerContent = generateLoaderHeader()
      const cppContent = generateLoaderCpp(allMessages, allEnums)
      fs.writeFileSync(path.join(outputDir, 'DataTableLoader.h'), headerContent, 'utf8')
      fs.writeFileSync(path.join(outputDir, 'DataTableLoader.cpp'), cppContent, 'utf8')
      generatedFiles.push('DataTableLoader.h')
      generatedFiles.push('DataTableLoader.cpp')
    }

    return generatedFiles
  }
}

export const unrealCodeGenerator = new UnrealCodeGeneratorService()

/** 필드 하나를 FJsonObject에서 읽어 멤버에 할당하는 C++ 코드 줄을 반환 (멤버 함수 맥락) */
function getFieldParseLines(
  field: ProtoField,
  allEnums: ProtoEnum[],
  allMessages: ProtoMessage[]
): string[] {
  const fn = field.name
  const jk = `TEXT("${fn}")`
  const isEnum = allEnums.some((e) => e.name === field.type)
  const isMsg = allMessages.some((m) => m.name === field.type)
  const prim = PRIMITIVE_MAP[field.type] ?? 'int32'

  if (field.isRepeated) {
    const lines: string[] = []
    lines.push(`    {`)
    lines.push(`        const TArray<TSharedPtr<FJsonValue>>* _Arr;`)
    lines.push(`        if (Obj->TryGetArrayField(${jk}, _Arr))`)
    lines.push(`        {`)
    lines.push(`            for (const auto& _Item : *_Arr)`)
    lines.push(`            {`)
    if (isEnum) {
      lines.push(
        `                FString _S; if (_Item->TryGetString(_S)) ${fn}.Add(ParseEnumFromString<E${field.type}>(_S));`
      )
    } else if (isMsg) {
      lines.push(`                const TSharedPtr<FJsonObject>* _Sub;`)
      lines.push(
        `                if (_Item->TryGetObject(_Sub)) { F${field.type} _R; _R.ParseFromJson(*_Sub); ${fn}.Add(_R); }`
      )
    } else if (prim === 'FString') {
      lines.push(`                FString _S; if (_Item->TryGetString(_S)) ${fn}.Add(_S);`)
    } else if (prim === 'bool') {
      lines.push(`                bool _B = false; if (_Item->TryGetBool(_B)) ${fn}.Add(_B);`)
    } else {
      lines.push(
        `                double _N = 0; if (_Item->TryGetNumber(_N)) ${fn}.Add(static_cast<${prim}>(_N));`
      )
    }
    lines.push(`            }`)
    lines.push(`        }`)
    lines.push(`    }`)
    return lines
  }

  // 단일 값
  if (isEnum) {
    return [
      `    { FString _S; if (Obj->TryGetStringField(${jk}, _S)) ${fn} = ParseEnumFromString<E${field.type}>(_S); }`
    ]
  }
  if (isMsg) {
    return [
      `    { const TSharedPtr<FJsonObject>* _O; if (Obj->TryGetObjectField(${jk}, _O)) ${fn}.ParseFromJson(*_O); }`
    ]
  }
  if (prim === 'FString') return [`    Obj->TryGetStringField(${jk}, ${fn});`]
  if (prim === 'bool') return [`    Obj->TryGetBoolField(${jk}, ${fn});`]
  return [
    `    { double _N; if (Obj->TryGetNumberField(${jk}, _N)) ${fn} = static_cast<${prim}>(_N); }`
  ]
}

/** DataTableLoader.h 내용 생성 — 단일 템플릿 함수 (헤더 온리) */
function generateLoaderHeader(): string {
  const parts: string[] = []
  parts.push(`// Auto-generated by DataManager. DO NOT EDIT.`)
  parts.push(`#pragma once`)
  parts.push(``)
  parts.push(`#include "CoreMinimal.h"`)
  parts.push(`#include "DataTables.h"`)
  parts.push(`#include "Misc/FileHelper.h"`)
  parts.push(`#include "Serialization/JsonReader.h"`)
  parts.push(`#include "Serialization/JsonSerializer.h"`)
  parts.push(`#include "Dom/JsonObject.h"`)
  parts.push(`#include "Dom/JsonValue.h"`)
  parts.push(``)
  parts.push(`/**`)
  parts.push(` * JSON 파일에서 데이터를 읽어 구조체 배열로 변환하는 유틸리티.`)
  parts.push(` * T 는 ParseFromJson(const TSharedPtr<FJsonObject>&) 멤버를 가져야 합니다.`)
  parts.push(` *`)
  parts.push(` * 사용 예:`)
  parts.push(` *   TArray<FMonster> Rows;`)
  parts.push(` *   UDataTableLoader::LoadFromJson<FMonster>(TEXT("Monster.json"), Rows);`)
  parts.push(` */`)
  parts.push(`struct UDataTableLoader`)
  parts.push(`{`)
  parts.push(`    template<typename T>`)
  parts.push(`    static bool LoadFromJson(const FString& FilePath, TArray<T>& OutRows)`)
  parts.push(`    {`)
  parts.push(`        FString JsonString;`)
  parts.push(`        if (!FFileHelper::LoadFileToString(JsonString, *FilePath)) return false;`)
  parts.push(``)
  parts.push(`        TArray<TSharedPtr<FJsonValue>> JsonArr;`)
  parts.push(`        TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonString);`)
  parts.push(`        if (!FJsonSerializer::Deserialize(Reader, JsonArr)) return false;`)
  parts.push(``)
  parts.push(`        OutRows.Empty();`)
  parts.push(`        for (const auto& Val : JsonArr)`)
  parts.push(`        {`)
  parts.push(`            const TSharedPtr<FJsonObject>* ObjPtr;`)
  parts.push(`            if (!Val->TryGetObject(ObjPtr)) continue;`)
  parts.push(`            T Row;`)
  parts.push(`            Row.ParseFromJson(*ObjPtr);`)
  parts.push(`            OutRows.Add(Row);`)
  parts.push(`        }`)
  parts.push(`        return true;`)
  parts.push(`    }`)
  parts.push(`};`)
  parts.push(``)
  return parts.join('\n')
}

/** DataTableLoader.cpp 내용 생성 — 각 struct의 ParseFromJson 멤버 구현 */
function generateLoaderCpp(allMessages: ProtoMessage[], allEnums: ProtoEnum[]): string {
  const parts: string[] = []
  parts.push(`// Auto-generated by DataManager. DO NOT EDIT.`)
  parts.push(`#include "DataTableLoader.h"`)
  parts.push(`#include "Dom/JsonObject.h"`)
  parts.push(`#include "Dom/JsonValue.h"`)
  parts.push(``)
  parts.push(`namespace`)
  parts.push(`{`)
  parts.push(``)
  parts.push(`template <typename TEnum>`)
  parts.push(`TEnum ParseEnumFromString(const FString& Str)`)
  parts.push(`{`)
  parts.push(`    const UEnum* E = StaticEnum<TEnum>();`)
  parts.push(`    if (E)`)
  parts.push(`    {`)
  parts.push(`        const int64 V = E->GetValueByNameString(Str);`)
  parts.push(`        if (V != INDEX_NONE) return static_cast<TEnum>(V);`)
  parts.push(`    }`)
  parts.push(`    return static_cast<TEnum>(0);`)
  parts.push(`}`)
  parts.push(``)
  parts.push(`} // namespace`)
  parts.push(``)
  for (const msg of allMessages) {
    parts.push(`void F${msg.name}::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)`)
    parts.push(`{`)
    for (const field of msg.fields) {
      const lines = getFieldParseLines(field, allEnums, allMessages)
      parts.push(...lines)
    }
    parts.push(`}`)
    parts.push(``)
  }
  return parts.join('\n')
}
