// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: KeyTable.proto

package DATA_MANAGER_FIXTURE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	Id    int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label string       `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	State FixtureState `protobuf:"varint,3,opt,name=state,proto3,enum=DATA_MANAGER_FIXTURE.FixtureState" json:"state,omitempty"`
}

func (x *SingleTarget) Reset() {
	*x = SingleTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyTable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleTarget) ProtoMessage() {}

func (x *SingleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_KeyTable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleTarget.ProtoReflect.Descriptor instead.
func (*SingleTarget) Descriptor() ([]byte, []int) {
	return file_KeyTable_proto_rawDescGZIP(), []int{0}
}

func (x *SingleTarget) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SingleTarget) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SingleTarget) GetState() FixtureState {
	if x != nil {
		return x.State
	}
	return FixtureState_FixtureState_NONE
}

type CompositeTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	Region int32 `protobuf:"varint,1,opt,name=region,proto3" json:"region,omitempty"`
	// @PK
	Id    int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *CompositeTarget) Reset() {
	*x = CompositeTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyTable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompositeTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeTarget) ProtoMessage() {}

func (x *CompositeTarget) ProtoReflect() protoreflect.Message {
	mi := &file_KeyTable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeTarget.ProtoReflect.Descriptor instead.
func (*CompositeTarget) Descriptor() ([]byte, []int) {
	return file_KeyTable_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeTarget) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

func (x *CompositeTarget) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompositeTarget) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GroupTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @Key
	GroupId int32  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Label   string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *GroupTarget) Reset() {
	*x = GroupTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyTable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTarget) ProtoMessage() {}

func (x *GroupTarget) ProtoReflect() protoreflect.Message {
	mi := &file_KeyTable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTarget.ProtoReflect.Descriptor instead.
func (*GroupTarget) Descriptor() ([]byte, []int) {
	return file_KeyTable_proto_rawDescGZIP(), []int{2}
}

func (x *GroupTarget) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupTarget) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type NoKeyTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *NoKeyTarget) Reset() {
	*x = NoKeyTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyTable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoKeyTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoKeyTarget) ProtoMessage() {}

func (x *NoKeyTarget) ProtoReflect() protoreflect.Message {
	mi := &file_KeyTable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoKeyTarget.ProtoReflect.Descriptor instead.
func (*NoKeyTarget) Descriptor() ([]byte, []int) {
	return file_KeyTable_proto_rawDescGZIP(), []int{3}
}

func (x *NoKeyTarget) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_KeyTable_proto protoreflect.FileDescriptor

var file_KeyTable_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46,
	0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x1a, 0x15, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a,
	0x0c, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45,
	0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x2e, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a,
	0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x3d,
	0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x23, 0x0a,
	0x0b, 0x4e, 0x6f, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e,
	0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_KeyTable_proto_rawDescOnce sync.Once
	file_KeyTable_proto_rawDescData = file_KeyTable_proto_rawDesc
)

func file_KeyTable_proto_rawDescGZIP() []byte {
	file_KeyTable_proto_rawDescOnce.Do(func() {
		file_KeyTable_proto_rawDescData = protoimpl.X.CompressGZIP(file_KeyTable_proto_rawDescData)
	})
	return file_KeyTable_proto_rawDescData
}

var file_KeyTable_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_KeyTable_proto_goTypes = []interface{}{
	(*SingleTarget)(nil),    // 0: DATA_MANAGER_FIXTURE.SingleTarget
	(*CompositeTarget)(nil), // 1: DATA_MANAGER_FIXTURE.CompositeTarget
	(*GroupTarget)(nil),     // 2: DATA_MANAGER_FIXTURE.GroupTarget
	(*NoKeyTarget)(nil),     // 3: DATA_MANAGER_FIXTURE.NoKeyTarget
	(FixtureState)(0),       // 4: DATA_MANAGER_FIXTURE.FixtureState
}
var file_KeyTable_proto_depIdxs = []int32{
	4, // 0: DATA_MANAGER_FIXTURE.SingleTarget.state:type_name -> DATA_MANAGER_FIXTURE.FixtureState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_KeyTable_proto_init() }
func file_KeyTable_proto_init() {
	if File_KeyTable_proto != nil {
		return
	}
	file_FixtureEnumType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_KeyTable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyTable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompositeTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyTable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyTable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoKeyTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KeyTable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KeyTable_proto_goTypes,
		DependencyIndexes: file_KeyTable_proto_depIdxs,
		MessageInfos:      file_KeyTable_proto_msgTypes,
	}.Build()
	File_KeyTable_proto = out.File
	file_KeyTable_proto_rawDesc = nil
	file_KeyTable_proto_goTypes = nil
	file_KeyTable_proto_depIdxs = nil
}
