// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: ReferenceTable.proto

package DATA_MANAGER_FIXTURE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiddleTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	Id     int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Single *SingleTarget `protobuf:"bytes,2,opt,name=single,proto3" json:"single,omitempty"`
}

func (x *MiddleTarget) Reset() {
	*x = MiddleTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReferenceTable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiddleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddleTarget) ProtoMessage() {}

func (x *MiddleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_ReferenceTable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddleTarget.ProtoReflect.Descriptor instead.
func (*MiddleTarget) Descriptor() ([]byte, []int) {
	return file_ReferenceTable_proto_rawDescGZIP(), []int{0}
}

func (x *MiddleTarget) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MiddleTarget) GetSingle() *SingleTarget {
	if x != nil {
		return x.Single
	}
	return nil
}

type RootTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	Id        int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Single    *SingleTarget    `protobuf:"bytes,2,opt,name=single,proto3" json:"single,omitempty"`
	Composite *CompositeTarget `protobuf:"bytes,3,opt,name=composite,proto3" json:"composite,omitempty"`
	Group     *GroupTarget     `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Middle    *MiddleTarget    `protobuf:"bytes,5,opt,name=middle,proto3" json:"middle,omitempty"`
	NoKey     *NoKeyTarget     `protobuf:"bytes,6,opt,name=noKey,proto3" json:"noKey,omitempty"`
	State     FixtureState     `protobuf:"varint,7,opt,name=state,proto3,enum=DATA_MANAGER_FIXTURE.FixtureState" json:"state,omitempty"`
}

func (x *RootTarget) Reset() {
	*x = RootTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReferenceTable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootTarget) ProtoMessage() {}

func (x *RootTarget) ProtoReflect() protoreflect.Message {
	mi := &file_ReferenceTable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootTarget.ProtoReflect.Descriptor instead.
func (*RootTarget) Descriptor() ([]byte, []int) {
	return file_ReferenceTable_proto_rawDescGZIP(), []int{1}
}

func (x *RootTarget) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RootTarget) GetSingle() *SingleTarget {
	if x != nil {
		return x.Single
	}
	return nil
}

func (x *RootTarget) GetComposite() *CompositeTarget {
	if x != nil {
		return x.Composite
	}
	return nil
}

func (x *RootTarget) GetGroup() *GroupTarget {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *RootTarget) GetMiddle() *MiddleTarget {
	if x != nil {
		return x.Middle
	}
	return nil
}

func (x *RootTarget) GetNoKey() *NoKeyTarget {
	if x != nil {
		return x.NoKey
	}
	return nil
}

func (x *RootTarget) GetState() FixtureState {
	if x != nil {
		return x.State
	}
	return FixtureState_FixtureState_NONE
}

type CycleA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	Id int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	B  *CycleB `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *CycleA) Reset() {
	*x = CycleA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReferenceTable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleA) ProtoMessage() {}

func (x *CycleA) ProtoReflect() protoreflect.Message {
	mi := &file_ReferenceTable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleA.ProtoReflect.Descriptor instead.
func (*CycleA) Descriptor() ([]byte, []int) {
	return file_ReferenceTable_proto_rawDescGZIP(), []int{2}
}

func (x *CycleA) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CycleA) GetB() *CycleB {
	if x != nil {
		return x.B
	}
	return nil
}

type CycleB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	Id int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	A  *CycleA `protobuf:"bytes,2,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *CycleB) Reset() {
	*x = CycleB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReferenceTable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleB) ProtoMessage() {}

func (x *CycleB) ProtoReflect() protoreflect.Message {
	mi := &file_ReferenceTable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleB.ProtoReflect.Descriptor instead.
func (*CycleB) Descriptor() ([]byte, []int) {
	return file_ReferenceTable_proto_rawDescGZIP(), []int{3}
}

func (x *CycleB) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CycleB) GetA() *CycleA {
	if x != nil {
		return x.A
	}
	return nil
}

var File_ReferenceTable_proto protoreflect.FileDescriptor

var file_ReferenceTable_proto_rawDesc = []byte{
	0x0a, 0x14, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e,
	0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x1a, 0x15, 0x46, 0x69,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0c, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47,
	0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x22,
	0x85, 0x03, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a,
	0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49,
	0x58, 0x54, 0x55, 0x52, 0x45, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x43, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58,
	0x54, 0x55, 0x52, 0x45, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x37, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49,
	0x58, 0x54, 0x55, 0x52, 0x45, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x3a, 0x0a, 0x06, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f,
	0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x2e,
	0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x6d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x6e, 0x6f, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47,
	0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x2e, 0x4e, 0x6f, 0x4b, 0x65, 0x79,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x05, 0x6e, 0x6f, 0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x44,
	0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54,
	0x55, 0x52, 0x45, 0x2e, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x44, 0x0a, 0x06, 0x43, 0x79, 0x63, 0x6c, 0x65,
	0x41, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2a, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x44,
	0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54,
	0x55, 0x52, 0x45, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x42, 0x52, 0x01, 0x62, 0x22, 0x44, 0x0a,
	0x06, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x42, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45,
	0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x41,
	0x52, 0x01, 0x61, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41,
	0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ReferenceTable_proto_rawDescOnce sync.Once
	file_ReferenceTable_proto_rawDescData = file_ReferenceTable_proto_rawDesc
)

func file_ReferenceTable_proto_rawDescGZIP() []byte {
	file_ReferenceTable_proto_rawDescOnce.Do(func() {
		file_ReferenceTable_proto_rawDescData = protoimpl.X.CompressGZIP(file_ReferenceTable_proto_rawDescData)
	})
	return file_ReferenceTable_proto_rawDescData
}

var file_ReferenceTable_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ReferenceTable_proto_goTypes = []interface{}{
	(*MiddleTarget)(nil),    // 0: DATA_MANAGER_FIXTURE.MiddleTarget
	(*RootTarget)(nil),      // 1: DATA_MANAGER_FIXTURE.RootTarget
	(*CycleA)(nil),          // 2: DATA_MANAGER_FIXTURE.CycleA
	(*CycleB)(nil),          // 3: DATA_MANAGER_FIXTURE.CycleB
	(*SingleTarget)(nil),    // 4: DATA_MANAGER_FIXTURE.SingleTarget
	(*CompositeTarget)(nil), // 5: DATA_MANAGER_FIXTURE.CompositeTarget
	(*GroupTarget)(nil),     // 6: DATA_MANAGER_FIXTURE.GroupTarget
	(*NoKeyTarget)(nil),     // 7: DATA_MANAGER_FIXTURE.NoKeyTarget
	(FixtureState)(0),       // 8: DATA_MANAGER_FIXTURE.FixtureState
}
var file_ReferenceTable_proto_depIdxs = []int32{
	4, // 0: DATA_MANAGER_FIXTURE.MiddleTarget.single:type_name -> DATA_MANAGER_FIXTURE.SingleTarget
	4, // 1: DATA_MANAGER_FIXTURE.RootTarget.single:type_name -> DATA_MANAGER_FIXTURE.SingleTarget
	5, // 2: DATA_MANAGER_FIXTURE.RootTarget.composite:type_name -> DATA_MANAGER_FIXTURE.CompositeTarget
	6, // 3: DATA_MANAGER_FIXTURE.RootTarget.group:type_name -> DATA_MANAGER_FIXTURE.GroupTarget
	0, // 4: DATA_MANAGER_FIXTURE.RootTarget.middle:type_name -> DATA_MANAGER_FIXTURE.MiddleTarget
	7, // 5: DATA_MANAGER_FIXTURE.RootTarget.noKey:type_name -> DATA_MANAGER_FIXTURE.NoKeyTarget
	8, // 6: DATA_MANAGER_FIXTURE.RootTarget.state:type_name -> DATA_MANAGER_FIXTURE.FixtureState
	3, // 7: DATA_MANAGER_FIXTURE.CycleA.b:type_name -> DATA_MANAGER_FIXTURE.CycleB
	2, // 8: DATA_MANAGER_FIXTURE.CycleB.a:type_name -> DATA_MANAGER_FIXTURE.CycleA
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_ReferenceTable_proto_init() }
func file_ReferenceTable_proto_init() {
	if File_ReferenceTable_proto != nil {
		return
	}
	file_FixtureEnumType_proto_init()
	file_KeyTable_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ReferenceTable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiddleTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ReferenceTable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ReferenceTable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ReferenceTable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ReferenceTable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ReferenceTable_proto_goTypes,
		DependencyIndexes: file_ReferenceTable_proto_depIdxs,
		MessageInfos:      file_ReferenceTable_proto_msgTypes,
	}.Build()
	File_ReferenceTable_proto = out.File
	file_ReferenceTable_proto_rawDesc = nil
	file_ReferenceTable_proto_goTypes = nil
	file_ReferenceTable_proto_depIdxs = nil
}
