import type {
  ProtoEnumDeclaration,
  ProtoFieldDeclaration,
  ProtoMessageDeclaration,
  ProtoWorkspace
} from './proto/model'

export interface UnrealGeneratedFile {
  fileName: string
  contents: string
}

export interface UnrealGenerationDiagnostic extends DiagnosticLike {
  code: string
  message: string
  sourceFile: string
  declarationName: string
}

export interface UnrealGenerationResult {
  files: UnrealGeneratedFile[]
  diagnostics: UnrealGenerationDiagnostic[]
}

const primitiveTypes: Record<string, string> = {
  string: 'FString',
  int32: 'int32',
  int64: 'int64',
  uint32: 'uint32',
  uint64: 'uint64',
  sint32: 'int32',
  sint64: 'int64',
  fixed32: 'uint32',
  fixed64: 'uint64',
  sfixed32: 'int32',
  sfixed64: 'int64',
  float: 'float',
  double: 'double',
  bool: 'bool',
  bytes: 'TArray<uint8>'
}

const protoPrimitiveTypes = new Set(Object.keys(primitiveTypes))

const primitiveDefaults: Record<string, string> = {
  FString: 'TEXT("")',
  int32: '0',
  int64: '0',
  uint32: '0',
  uint64: '0',
  float: '0.0f',
  double: '0.0',
  bool: 'false'
}

export function generateUnrealFiles(workspace: ProtoWorkspace): UnrealGenerationResult {
  const diagnostics = validateUnrealWorkspace(workspace)
  if (diagnostics.some(({ code }) => code !== 'UNREAL_MESSAGE_CYCLE_POINTER')) {
    return { files: [], diagnostics }
  }
  const files: UnrealGeneratedFile[] = []
  const enumsByFile = new Map<string, ProtoEnumDeclaration[]>()
  for (const declaration of workspace.enums) {
    const declarations = enumsByFile.get(declaration.sourceFile) ?? []
    declarations.push(declaration)
    enumsByFile.set(declaration.sourceFile, declarations)
  }
  for (const [sourceFile, declarations] of [...enumsByFile].sort(([left], [right]) =>
    left.localeCompare(right, 'en')
  )) {
    const baseName = sourceFile.replace(/\.proto$/, '')
    files.push({
      fileName: `${baseName}.h`,
      contents: joinLines([
        '// Auto-generated by DataManager. DO NOT EDIT.',
        '#pragma once',
        '',
        '#include "CoreMinimal.h"',
        `#include "${baseName}.generated.h"`,
        ...declarations.flatMap((declaration) => ['', generateEnum(declaration)])
      ])
    })
  }

  if (workspace.messages.length > 0) {
    const cyclicFields = findCyclicFields(workspace.messages)
    const orderedMessages = orderMessages(workspace.messages, cyclicFields)
    files.push({
      fileName: 'DataTables.h',
      contents: generateDataTables(workspace, orderedMessages, cyclicFields)
    })
    files.push({ fileName: 'DataTableLoader.h', contents: generateLoaderHeader() })
    files.push({
      fileName: 'DataTableLoader.cpp',
      contents: generateLoaderCpp(workspace, orderedMessages, cyclicFields)
    })
  }
  return { files, diagnostics }
}

function validateUnrealWorkspace(workspace: ProtoWorkspace): UnrealGenerationDiagnostic[] {
  const diagnostics: UnrealGenerationDiagnostic[] = []
  for (const declaration of workspace.enums) {
    for (const value of declaration.values) {
      if (value.number < 0 || value.number > 255) {
        diagnostics.push({
          code: 'UNREAL_ENUM_VALUE_OUT_OF_RANGE',
          message: `Blueprint Enum '${declaration.name}' value '${value.name}' must fit uint8.`,
          sourceFile: declaration.sourceFile,
          declarationName: declaration.name
        })
      }
    }
  }
  for (const declaration of workspace.messages) {
    for (const field of declaration.fields) {
      const type = unqualified(field.type)
      const resolved =
        protoPrimitiveTypes.has(type) ||
        workspace.enums.some(({ name }) => name === type) ||
        workspace.messages.some(({ name }) => name === type)
      if (!resolved) {
        diagnostics.push({
          code: 'UNREAL_UNRESOLVED_FIELD_TYPE',
          message: `Field '${declaration.name}.${field.name}' has unresolved type '${field.type}'.`,
          sourceFile: declaration.sourceFile,
          declarationName: declaration.name
        })
      }
    }
  }
  for (const field of findCyclicFields(workspace.messages)) {
    const [sourceName, fieldName] = field.split(':')
    const source = workspace.messages.find(({ name }) => name === sourceName)
    if (!source || !sourceName) continue
    diagnostics.push({
      code: 'UNREAL_MESSAGE_CYCLE_POINTER',
      message: `Cyclic field '${sourceName}.${fieldName}' is generated as TSharedPtr.`,
      sourceFile: source.sourceFile,
      declarationName: sourceName
    })
  }
  return diagnostics
}

function generateEnum(declaration: ProtoEnumDeclaration): string {
  return [
    'UENUM(BlueprintType)',
    `enum class E${declaration.name} : uint8`,
    '{',
    ...declaration.values.map(
      (value) => `    ${value.name} = ${value.number} UMETA(DisplayName = "${value.name}"),`
    ),
    '};'
  ].join('\n')
}

function generateDataTables(
  workspace: ProtoWorkspace,
  messages: readonly ProtoMessageDeclaration[],
  cyclicFields: ReadonlySet<string>
): string {
  const enumIncludes = [
    ...new Set(
      workspace.messages.flatMap((message) =>
        message.fields
          .map((field) => workspace.enums.find(({ name }) => name === unqualified(field.type)))
          .filter((value): value is ProtoEnumDeclaration => Boolean(value))
          .map((value) => value.sourceFile.replace(/\.proto$/, '.h'))
      )
    )
  ].sort((left, right) => left.localeCompare(right, 'en'))
  return joinLines([
    '// Auto-generated by DataManager. DO NOT EDIT.',
    '#pragma once',
    '',
    '#include "CoreMinimal.h"',
    '#include "Engine/DataTable.h"',
    ...enumIncludes.map((file) => `#include "${file}"`),
    '#include "DataTables.generated.h"',
    '',
    'class FJsonObject;',
    '',
    ...messages.map((message) => `struct F${message.name};`),
    ...messages.flatMap((message) => ['', generateStruct(workspace, message, cyclicFields)])
  ])
}

function generateStruct(
  workspace: ProtoWorkspace,
  message: ProtoMessageDeclaration,
  cyclicFields: ReadonlySet<string>
): string {
  const lines = [
    'USTRUCT(BlueprintType)',
    `struct F${message.name} : public FTableRowBase`,
    '{',
    '    GENERATED_BODY()'
  ]
  for (const field of message.fields) {
    const cyclic = cyclicFields.has(`${message.name}:${field.name}`)
    const type = unrealType(workspace, field, cyclic)
    const defaultValue = unrealDefault(workspace, field, cyclic)
    lines.push('')
    if (!cyclic) lines.push('    UPROPERTY(EditAnywhere, BlueprintReadWrite)')
    else lines.push('    // Cyclic references are not reflected as UPROPERTY values.')
    lines.push(`    ${type} ${field.name}${defaultValue ? ` = ${defaultValue}` : ''};`)
  }
  lines.push('', '    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);', '};')
  return lines.join('\n')
}

function unrealType(
  workspace: ProtoWorkspace,
  field: ProtoFieldDeclaration,
  cyclic: boolean
): string {
  const type = unqualified(field.type)
  let base: string
  if (workspace.enums.some(({ name }) => name === type)) base = `E${type}`
  else if (workspace.messages.some(({ name }) => name === type)) {
    base = cyclic ? `TSharedPtr<F${type}>` : `F${type}`
  } else base = primitiveTypes[type] ?? 'int32'
  return field.label === 'repeated' ? `TArray<${base}>` : base
}

function unrealDefault(
  workspace: ProtoWorkspace,
  field: ProtoFieldDeclaration,
  cyclic: boolean
): string {
  if (field.label === 'repeated' || cyclic) return ''
  const type = unqualified(field.type)
  if (workspace.enums.some(({ name }) => name === type)) return `static_cast<E${type}>(0)`
  if (workspace.messages.some(({ name }) => name === type)) return ''
  return primitiveDefaults[primitiveTypes[type] ?? ''] ?? ''
}

function generateLoaderHeader(): string {
  return joinLines([
    '// Auto-generated by DataManager. DO NOT EDIT.',
    '#pragma once',
    '',
    '#include "CoreMinimal.h"',
    '#include "DataTables.h"',
    '#include "Misc/FileHelper.h"',
    '#include "Serialization/JsonReader.h"',
    '#include "Serialization/JsonSerializer.h"',
    '#include "Dom/JsonObject.h"',
    '#include "Dom/JsonValue.h"',
    '',
    'struct FDataTableLoader',
    '{',
    '    template<typename T>',
    '    static bool LoadFromJson(const FString& FilePath, TArray<T>& OutRows)',
    '    {',
    '        FString JsonString;',
    '        if (!FFileHelper::LoadFileToString(JsonString, *FilePath)) return false;',
    '        TArray<TSharedPtr<FJsonValue>> JsonArray;',
    '        const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonString);',
    '        if (!FJsonSerializer::Deserialize(Reader, JsonArray)) return false;',
    '        OutRows.Reset();',
    '        for (const TSharedPtr<FJsonValue>& Value : JsonArray)',
    '        {',
    '            const TSharedPtr<FJsonObject>* Object;',
    '            if (!Value->TryGetObject(Object)) continue;',
    '            T Row;',
    '            Row.ParseFromJson(*Object);',
    '            OutRows.Add(MoveTemp(Row));',
    '        }',
    '        return true;',
    '    }',
    '};'
  ])
}

function generateLoaderCpp(
  workspace: ProtoWorkspace,
  messages: readonly ProtoMessageDeclaration[],
  cyclicFields: ReadonlySet<string>
): string {
  return joinLines([
    '// Auto-generated by DataManager. DO NOT EDIT.',
    '#include "DataTableLoader.h"',
    '#include "Misc/Base64.h"',
    '',
    'namespace',
    '{',
    'template <typename TEnum>',
    'TEnum ParseEnumFromString(const FString& Value)',
    '{',
    '    const UEnum* Enum = StaticEnum<TEnum>();',
    '    if (Enum)',
    '    {',
    '        const int64 Number = Enum->GetValueByNameString(Value);',
    '        if (Number != INDEX_NONE) return static_cast<TEnum>(Number);',
    '    }',
    '    return static_cast<TEnum>(0);',
    '}',
    '} // namespace',
    ...messages.flatMap((message) => [
      '',
      `void F${message.name}::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)`,
      '{',
      ...message.fields.flatMap((field) =>
        parseFieldLines(workspace, field, cyclicFields.has(`${message.name}:${field.name}`))
      ),
      '}'
    ])
  ])
}

function parseFieldLines(
  workspace: ProtoWorkspace,
  field: ProtoFieldDeclaration,
  cyclic: boolean
): string[] {
  const name = field.name
  const key = `TEXT("${name}")`
  const type = unqualified(field.type)
  const isEnum = workspace.enums.some(({ name: candidate }) => candidate === type)
  const isMessage = workspace.messages.some(({ name: candidate }) => candidate === type)
  const primitive = primitiveTypes[type] ?? 'int32'
  if (field.label === 'repeated') {
    const add = isEnum
      ? `${name}.Add(ParseEnumFromString<E${type}>(Text));`
      : isMessage
        ? `${cyclic ? `TSharedPtr<F${type}> Row = MakeShared<F${type}>(); Row->ParseFromJson(*Object); ${name}.Add(Row);` : `F${type} Row; Row.ParseFromJson(*Object); ${name}.Add(MoveTemp(Row));`}`
        : type === 'bytes'
          ? `TArray<uint8> Bytes; if (FBase64::Decode(Text, Bytes)) ${name}.Add(MoveTemp(Bytes));`
          : primitive === 'FString'
            ? `${name}.Add(Text);`
            : primitive === 'bool'
              ? `${name}.Add(Boolean);`
              : `${name}.Add(static_cast<${primitive}>(Number));`
    const extraction = isMessage
      ? `const TSharedPtr<FJsonObject>* Object; if (Item->TryGetObject(Object)) { ${add} }`
      : primitive === 'bool'
        ? `bool Boolean = false; if (Item->TryGetBool(Boolean)) { ${add} }`
        : isEnum || primitive === 'FString' || type === 'bytes'
          ? `FString Text; if (Item->TryGetString(Text)) { ${add} }`
          : `double Number = 0; if (Item->TryGetNumber(Number)) { ${add} }`
    return [
      '    {',
      '        const TArray<TSharedPtr<FJsonValue>>* Array;',
      `        if (Obj->TryGetArrayField(${key}, Array))`,
      '        {',
      `            ${name}.Reset();`,
      `            for (const TSharedPtr<FJsonValue>& Item : *Array) { ${extraction} }`,
      '        }',
      '    }'
    ]
  }
  if (isEnum) {
    return [
      `    { FString Value; if (Obj->TryGetStringField(${key}, Value)) ${name} = ParseEnumFromString<E${type}>(Value); }`
    ]
  }
  if (isMessage) {
    if (cyclic) {
      return [
        `    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(${key}, Value)) { ${name} = MakeShared<F${type}>(); ${name}->ParseFromJson(*Value); } }`
      ]
    }
    return [
      `    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(${key}, Value)) ${name}.ParseFromJson(*Value); }`
    ]
  }
  if (type === 'bytes') {
    return [
      `    { FString Value; if (Obj->TryGetStringField(${key}, Value)) FBase64::Decode(Value, ${name}); }`
    ]
  }
  if (primitive === 'FString') return [`    Obj->TryGetStringField(${key}, ${name});`]
  if (primitive === 'bool') return [`    Obj->TryGetBoolField(${key}, ${name});`]
  return [
    `    { double Value = 0; if (Obj->TryGetNumberField(${key}, Value)) ${name} = static_cast<${primitive}>(Value); }`
  ]
}

function orderMessages(
  messages: readonly ProtoMessageDeclaration[],
  cyclicFields: ReadonlySet<string>
): ProtoMessageDeclaration[] {
  const byName = new Map(messages.map((message) => [message.name, message]))
  const visited = new Set<string>()
  const result: ProtoMessageDeclaration[] = []
  const visit = (message: ProtoMessageDeclaration): void => {
    if (visited.has(message.name)) return
    visited.add(message.name)
    message.fields
      .filter((field) => !cyclicFields.has(`${message.name}:${field.name}`))
      .map((field) => byName.get(unqualified(field.type)))
      .filter((value): value is ProtoMessageDeclaration => Boolean(value))
      .sort((left, right) => left.name.localeCompare(right.name, 'en'))
      .forEach(visit)
    result.push(message)
  }
  ;[...messages].sort((left, right) => left.name.localeCompare(right.name, 'en')).forEach(visit)
  return result
}

function findCyclicFields(messages: readonly ProtoMessageDeclaration[]): Set<string> {
  const byName = new Map(messages.map((message) => [message.name, message]))
  const dependsOn = (start: string, target: string, visited = new Set<string>()): boolean => {
    if (start === target) return true
    if (visited.has(start)) return false
    visited.add(start)
    const message = byName.get(start)
    const reachable = Boolean(
      message?.fields.some((field) => {
        const dependency = unqualified(field.type)
        return byName.has(dependency) && dependsOn(dependency, target, visited)
      })
    )
    visited.delete(start)
    return reachable
  }
  const cyclic = new Set<string>()
  for (const message of messages) {
    for (const field of message.fields) {
      const target = unqualified(field.type)
      if (byName.has(target) && dependsOn(target, message.name)) {
        cyclic.add(`${message.name}:${field.name}`)
      }
    }
  }
  return cyclic
}

function joinLines(lines: readonly string[]): string {
  return `${lines.join('\n')}\n`
}

function unqualified(type: string): string {
  return type.replace(/^\./, '').split('.').at(-1) ?? type
}
import type { DiagnosticLike } from './diagnostics'
