// Auto-generated by DataManager. DO NOT EDIT.
#pragma once

#include "CoreMinimal.h"
#include "CommonEnumType.generated.h"

UENUM(BlueprintType)
enum class EGradeType : uint8
{
    GradeType_GradeType_NONE = 0 UMETA(DisplayName = "GradeType_NONE"),
    GradeType_GradeType_NORMAL = 1 UMETA(DisplayName = "GradeType_NORMAL"),
    GradeType_GradeType_SUPERIOR = 2 UMETA(DisplayName = "GradeType_SUPERIOR"),
    GradeType_GradeType_RARE = 3 UMETA(DisplayName = "GradeType_RARE"),
    GradeType_GradeType_EPIC = 4 UMETA(DisplayName = "GradeType_EPIC"),
    GradeType_GradeType_LEGENDARY = 5 UMETA(DisplayName = "GradeType_LEGENDARY"),
    GradeType_GradeType_MAX = 6 UMETA(DisplayName = "GradeType_MAX"),
};
