// Auto-generated by DataManager. DO NOT EDIT.
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "CommonEnumType.h"
#include "ItemEnumType.h"
#include "TestEnumType.h"
#include "DataTables.generated.h"

USTRUCT(BlueprintType)
struct FGameItemTypeDef : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    EItemType itemType = static_cast<EItemType>(0);

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString typeName = TEXT("");

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool isTradable = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString iconPath = TEXT("");

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FGameItem : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 itemId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString name = TEXT("");

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FGameItemTypeDef itemType;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    EGradeType rarity = static_cast<EGradeType>(0);

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 maxStack = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 price = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString descriptions = TEXT("");

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FMonsterRace : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 GroupID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FMonster MonsterID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Memo = 0;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FMonster : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 monsterId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FStringData name;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 hp = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 atk = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 def = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float moveSpeed = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FRewardItemGroup RewardGroupId;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FRewardItemGroup : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 GroupId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Memo = TEXT("");

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FGameItem RewardItemId01;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float RewardItemRate01 = 0.0f;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FStringData : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 ko = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 en = 0;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FGoTest : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 ID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    ETestType TestColumn = static_cast<ETestType>(0);

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Test23 = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Test45 = 0;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FNameTest : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 ID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FStringData Name;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};
