# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CategoryTable.proto

require 'google/protobuf'


descriptor_data = "\n\x13\x43\x61tegoryTable.proto\x12\x05\x64\x31\x30\x30\x30\"j\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x06parent\x18\x02 \x01(\x0b\x32\x0f.d1000.CategoryH\x00\x88\x01\x01\x12!\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x0f.d1000.CategoryB\t\n\x07_parentB\tZ\x07./d1000b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module D1000
  Category = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("d1000.Category").msgclass
end
