# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FixtureEnumType.proto

require 'google/protobuf'


descriptor_data = "\n\x15\x46ixtureEnumType.proto\x12\x14\x44\x41TA_MANAGER_FIXTURE*T\n\x0c\x46ixtureState\x12\x15\n\x11\x46ixtureState_NONE\x10\x00\x12\x17\n\x13\x46ixtureState_ACTIVE\x10\x01\x12\x14\n\x10\x46ixtureState_MAX\x10\x02\x42\x18Z\x16./DATA_MANAGER_FIXTUREb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module DATAMANAGERFIXTURE
  FixtureState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DATA_MANAGER_FIXTURE.FixtureState").enummodule
end
