// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: KeyTable.proto
// Protobuf C++ Version: 7.34.1

#include "KeyTable.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace DATA_MANAGER_FIXTURE {

inline constexpr SingleTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        state_{static_cast< ::DATA_MANAGER_FIXTURE::FixtureState >(0)} {}

template <typename>
constexpr SingleTarget::SingleTarget(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SingleTarget_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct SingleTargetDefaultTypeInternal {
  constexpr SingleTargetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SingleTargetDefaultTypeInternal() {}
  union {
    SingleTarget _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SingleTargetDefaultTypeInternal _SingleTarget_default_instance_;

inline constexpr NoKeyTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr NoKeyTarget::NoKeyTarget(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NoKeyTarget_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct NoKeyTargetDefaultTypeInternal {
  constexpr NoKeyTargetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NoKeyTargetDefaultTypeInternal() {}
  union {
    NoKeyTarget _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NoKeyTargetDefaultTypeInternal _NoKeyTarget_default_instance_;

inline constexpr GroupTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        groupid_{0} {}

template <typename>
constexpr GroupTarget::GroupTarget(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GroupTarget_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct GroupTargetDefaultTypeInternal {
  constexpr GroupTargetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GroupTargetDefaultTypeInternal() {}
  union {
    GroupTarget _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GroupTargetDefaultTypeInternal _GroupTarget_default_instance_;

inline constexpr CompositeTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        region_{0},
        id_{0} {}

template <typename>
constexpr CompositeTarget::CompositeTarget(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CompositeTarget_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CompositeTargetDefaultTypeInternal {
  constexpr CompositeTargetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompositeTargetDefaultTypeInternal() {}
  union {
    CompositeTarget _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompositeTargetDefaultTypeInternal _CompositeTarget_default_instance_;
}  // namespace DATA_MANAGER_FIXTURE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_KeyTable_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_KeyTable_2eproto = nullptr;
const ::uint32_t
    TableStruct_KeyTable_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::SingleTarget, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::SingleTarget, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::SingleTarget, _impl_.label_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::SingleTarget, _impl_.state_),
        1,
        0,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::CompositeTarget, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::CompositeTarget, _impl_.region_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::CompositeTarget, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::CompositeTarget, _impl_.label_),
        1,
        2,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::GroupTarget, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::GroupTarget, _impl_.groupid_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::GroupTarget, _impl_.label_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::NoKeyTarget, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_FIXTURE::NoKeyTarget, _impl_.label_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::DATA_MANAGER_FIXTURE::SingleTarget)},
        {9, sizeof(::DATA_MANAGER_FIXTURE::CompositeTarget)},
        {18, sizeof(::DATA_MANAGER_FIXTURE::GroupTarget)},
        {25, sizeof(::DATA_MANAGER_FIXTURE::NoKeyTarget)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::DATA_MANAGER_FIXTURE::_SingleTarget_default_instance_._instance,
    &::DATA_MANAGER_FIXTURE::_CompositeTarget_default_instance_._instance,
    &::DATA_MANAGER_FIXTURE::_GroupTarget_default_instance_._instance,
    &::DATA_MANAGER_FIXTURE::_NoKeyTarget_default_instance_._instance,
};
const char descriptor_table_protodef_KeyTable_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016KeyTable.proto\022\024DATA_MANAGER_FIXTURE\032\025"
    "FixtureEnumType.proto\"\\\n\014SingleTarget\022\n\n"
    "\002id\030\001 \001(\005\022\r\n\005label\030\002 \001(\t\0221\n\005state\030\003 \001(\0162"
    "\".DATA_MANAGER_FIXTURE.FixtureState\"<\n\017C"
    "ompositeTarget\022\016\n\006region\030\001 \001(\005\022\n\n\002id\030\002 \001"
    "(\005\022\r\n\005label\030\003 \001(\t\"-\n\013GroupTarget\022\017\n\007grou"
    "pId\030\001 \001(\005\022\r\n\005label\030\002 \001(\t\"\034\n\013NoKeyTarget\022"
    "\r\n\005label\030\001 \001(\tB\030Z\026./DATA_MANAGER_FIXTURE"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_KeyTable_2eproto_deps[1] = {
        &::descriptor_table_FixtureEnumType_2eproto,
};
static ::absl::once_flag descriptor_table_KeyTable_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_KeyTable_2eproto = {
    false,
    false,
    328,
    descriptor_table_protodef_KeyTable_2eproto,
    "KeyTable.proto",
    &descriptor_table_KeyTable_2eproto_once,
    descriptor_table_KeyTable_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_KeyTable_2eproto::offsets,
    file_level_enum_descriptors_KeyTable_2eproto,
    file_level_service_descriptors_KeyTable_2eproto,
};
namespace DATA_MANAGER_FIXTURE {
// ===================================================================

class SingleTarget::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SingleTarget>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_._has_bits_);
};

SingleTarget::SingleTarget(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SingleTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_FIXTURE.SingleTarget)
}
PROTOBUF_NDEBUG_INLINE SingleTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::DATA_MANAGER_FIXTURE::SingleTarget& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        label_(arena, from.label_) {}

SingleTarget::SingleTarget(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SingleTarget& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SingleTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SingleTarget* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, state_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::state_));

  // @@protoc_insertion_point(copy_constructor:DATA_MANAGER_FIXTURE.SingleTarget)
}
PROTOBUF_NDEBUG_INLINE SingleTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        label_(arena) {}

inline void SingleTarget::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, state_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::state_));
}
SingleTarget::~SingleTarget() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_FIXTURE.SingleTarget)
  SharedDtor(*this);
}
inline void SingleTarget::SharedDtor(MessageLite& self) {
  SingleTarget& this_ = static_cast<SingleTarget&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SingleTarget::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SingleTarget(arena);
}
constexpr auto SingleTarget::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SingleTarget),
                                            alignof(SingleTarget));
}
constexpr auto SingleTarget::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SingleTarget_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &SingleTarget::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SingleTarget>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SingleTarget::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SingleTarget>(), &SingleTarget::ByteSizeLong,
              &SingleTarget::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_._cached_size_),
          false,
      },
      &SingleTarget::kDescriptorMethods,
      &descriptor_table_KeyTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SingleTarget_class_data_ =
        SingleTarget::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SingleTarget::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SingleTarget_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SingleTarget_class_data_.tc_table);
  return SingleTarget_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 47, 2>
SingleTarget::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SingleTarget_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_FIXTURE::SingleTarget>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SingleTarget, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.id_)}},
    // string label = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.label_)}},
    // .DATA_MANAGER_FIXTURE.FixtureState state = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SingleTarget, _impl_.state_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string label = 2;
    {PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.label_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .DATA_MANAGER_FIXTURE.FixtureState state = 3;
    {PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.state_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\41\0\5\0\0\0\0\0"
    "DATA_MANAGER_FIXTURE.SingleTarget"
    "label"
  }},
};
PROTOBUF_NOINLINE void SingleTarget::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_FIXTURE.SingleTarget)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.label_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.state_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.state_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SingleTarget::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SingleTarget& this_ = static_cast<const SingleTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SingleTarget::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SingleTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_FIXTURE.SingleTarget)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string label = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_label().empty()) {
      const ::std::string& _s = this_._internal_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_FIXTURE.SingleTarget.label");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // .DATA_MANAGER_FIXTURE.FixtureState state = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_state() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          3, this_._internal_state(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_FIXTURE.SingleTarget)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SingleTarget::ByteSizeLong(const MessageLite& base) {
  const SingleTarget& this_ = static_cast<const SingleTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SingleTarget::ByteSizeLong() const {
  const SingleTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_FIXTURE.SingleTarget)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string label = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_label());
      }
    }
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // .DATA_MANAGER_FIXTURE.FixtureState state = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_state() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_state());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SingleTarget::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SingleTarget*>(&to_msg);
  auto& from = static_cast<const SingleTarget&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_FIXTURE.SingleTarget)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_label().empty()) {
        _this->_internal_set_label(from._internal_label());
      } else {
        if (_this->_impl_.label_.IsDefault()) {
          _this->_internal_set_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_state() != 0) {
        _this->_impl_.state_ = from._impl_.state_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SingleTarget::CopyFrom(const SingleTarget& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_FIXTURE.SingleTarget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SingleTarget::InternalSwap(SingleTarget* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.state_)
      + sizeof(SingleTarget::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(SingleTarget, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata SingleTarget::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CompositeTarget::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CompositeTarget>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_._has_bits_);
};

CompositeTarget::CompositeTarget(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CompositeTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_FIXTURE.CompositeTarget)
}
PROTOBUF_NDEBUG_INLINE CompositeTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::DATA_MANAGER_FIXTURE::CompositeTarget& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        label_(arena, from.label_) {}

CompositeTarget::CompositeTarget(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CompositeTarget& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CompositeTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CompositeTarget* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, region_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, region_),
           offsetof(Impl_, id_) -
               offsetof(Impl_, region_) +
               sizeof(Impl_::id_));

  // @@protoc_insertion_point(copy_constructor:DATA_MANAGER_FIXTURE.CompositeTarget)
}
PROTOBUF_NDEBUG_INLINE CompositeTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        label_(arena) {}

inline void CompositeTarget::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, region_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, region_) +
               sizeof(Impl_::id_));
}
CompositeTarget::~CompositeTarget() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_FIXTURE.CompositeTarget)
  SharedDtor(*this);
}
inline void CompositeTarget::SharedDtor(MessageLite& self) {
  CompositeTarget& this_ = static_cast<CompositeTarget&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CompositeTarget::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CompositeTarget(arena);
}
constexpr auto CompositeTarget::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CompositeTarget),
                                            alignof(CompositeTarget));
}
constexpr auto CompositeTarget::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CompositeTarget_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CompositeTarget::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CompositeTarget>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CompositeTarget::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CompositeTarget>(), &CompositeTarget::ByteSizeLong,
              &CompositeTarget::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_._cached_size_),
          false,
      },
      &CompositeTarget::kDescriptorMethods,
      &descriptor_table_KeyTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CompositeTarget_class_data_ =
        CompositeTarget::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CompositeTarget::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CompositeTarget_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CompositeTarget_class_data_.tc_table);
  return CompositeTarget_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 50, 2>
CompositeTarget::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CompositeTarget_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_FIXTURE::CompositeTarget>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 region = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CompositeTarget, _impl_.region_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.region_)}},
    // int32 id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CompositeTarget, _impl_.id_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.id_)}},
    // string label = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.label_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 region = 1;
    {PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.region_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 id = 2;
    {PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string label = 3;
    {PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.label_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\44\0\0\5\0\0\0\0"
    "DATA_MANAGER_FIXTURE.CompositeTarget"
    "label"
  }},
};
PROTOBUF_NOINLINE void CompositeTarget::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_FIXTURE.CompositeTarget)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.label_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.region_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.id_) -
        reinterpret_cast<char*>(&_impl_.region_)) + sizeof(_impl_.id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CompositeTarget::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CompositeTarget& this_ = static_cast<const CompositeTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CompositeTarget::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CompositeTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_FIXTURE.CompositeTarget)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 region = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_region() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_region(), target);
    }
  }

  // int32 id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_id(), target);
    }
  }

  // string label = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_label().empty()) {
      const ::std::string& _s = this_._internal_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_FIXTURE.CompositeTarget.label");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_FIXTURE.CompositeTarget)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CompositeTarget::ByteSizeLong(const MessageLite& base) {
  const CompositeTarget& this_ = static_cast<const CompositeTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CompositeTarget::ByteSizeLong() const {
  const CompositeTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_FIXTURE.CompositeTarget)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string label = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_label());
      }
    }
    // int32 region = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_region() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_region());
      }
    }
    // int32 id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CompositeTarget::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CompositeTarget*>(&to_msg);
  auto& from = static_cast<const CompositeTarget&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_FIXTURE.CompositeTarget)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_label().empty()) {
        _this->_internal_set_label(from._internal_label());
      } else {
        if (_this->_impl_.label_.IsDefault()) {
          _this->_internal_set_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_region() != 0) {
        _this->_impl_.region_ = from._impl_.region_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CompositeTarget::CopyFrom(const CompositeTarget& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_FIXTURE.CompositeTarget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CompositeTarget::InternalSwap(CompositeTarget* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.id_)
      + sizeof(CompositeTarget::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(CompositeTarget, _impl_.region_)>(
          reinterpret_cast<char*>(&_impl_.region_),
          reinterpret_cast<char*>(&other->_impl_.region_));
}

::google::protobuf::Metadata CompositeTarget::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GroupTarget::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GroupTarget>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_._has_bits_);
};

GroupTarget::GroupTarget(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GroupTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_FIXTURE.GroupTarget)
}
PROTOBUF_NDEBUG_INLINE GroupTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::DATA_MANAGER_FIXTURE::GroupTarget& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        label_(arena, from.label_) {}

GroupTarget::GroupTarget(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GroupTarget& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GroupTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GroupTarget* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.groupid_ = from._impl_.groupid_;

  // @@protoc_insertion_point(copy_constructor:DATA_MANAGER_FIXTURE.GroupTarget)
}
PROTOBUF_NDEBUG_INLINE GroupTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        label_(arena) {}

inline void GroupTarget::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.groupid_ = {};
}
GroupTarget::~GroupTarget() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_FIXTURE.GroupTarget)
  SharedDtor(*this);
}
inline void GroupTarget::SharedDtor(MessageLite& self) {
  GroupTarget& this_ = static_cast<GroupTarget&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GroupTarget::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GroupTarget(arena);
}
constexpr auto GroupTarget::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GroupTarget),
                                            alignof(GroupTarget));
}
constexpr auto GroupTarget::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GroupTarget_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &GroupTarget::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GroupTarget>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GroupTarget::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GroupTarget>(), &GroupTarget::ByteSizeLong,
              &GroupTarget::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_._cached_size_),
          false,
      },
      &GroupTarget::kDescriptorMethods,
      &descriptor_table_KeyTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GroupTarget_class_data_ =
        GroupTarget::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GroupTarget::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GroupTarget_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GroupTarget_class_data_.tc_table);
  return GroupTarget_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 46, 2>
GroupTarget::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GroupTarget_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_FIXTURE::GroupTarget>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string label = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_.label_)}},
    // int32 groupId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GroupTarget, _impl_.groupid_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_.groupid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 groupId = 1;
    {PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_.groupid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string label = 2;
    {PROTOBUF_FIELD_OFFSET(GroupTarget, _impl_.label_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\0\5\0\0\0\0\0"
    "DATA_MANAGER_FIXTURE.GroupTarget"
    "label"
  }},
};
PROTOBUF_NOINLINE void GroupTarget::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_FIXTURE.GroupTarget)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.label_.ClearNonDefaultToEmpty();
  }
  _impl_.groupid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GroupTarget::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GroupTarget& this_ = static_cast<const GroupTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GroupTarget::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GroupTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_FIXTURE.GroupTarget)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 groupId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_groupid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_groupid(), target);
    }
  }

  // string label = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_label().empty()) {
      const ::std::string& _s = this_._internal_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_FIXTURE.GroupTarget.label");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_FIXTURE.GroupTarget)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GroupTarget::ByteSizeLong(const MessageLite& base) {
  const GroupTarget& this_ = static_cast<const GroupTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GroupTarget::ByteSizeLong() const {
  const GroupTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_FIXTURE.GroupTarget)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string label = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_label());
      }
    }
    // int32 groupId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_groupid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_groupid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GroupTarget::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GroupTarget*>(&to_msg);
  auto& from = static_cast<const GroupTarget&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_FIXTURE.GroupTarget)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_label().empty()) {
        _this->_internal_set_label(from._internal_label());
      } else {
        if (_this->_impl_.label_.IsDefault()) {
          _this->_internal_set_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_groupid() != 0) {
        _this->_impl_.groupid_ = from._impl_.groupid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GroupTarget::CopyFrom(const GroupTarget& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_FIXTURE.GroupTarget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GroupTarget::InternalSwap(GroupTarget* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  swap(_impl_.groupid_, other->_impl_.groupid_);
}

::google::protobuf::Metadata GroupTarget::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NoKeyTarget::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NoKeyTarget>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NoKeyTarget, _impl_._has_bits_);
};

NoKeyTarget::NoKeyTarget(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NoKeyTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_FIXTURE.NoKeyTarget)
}
PROTOBUF_NDEBUG_INLINE NoKeyTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::DATA_MANAGER_FIXTURE::NoKeyTarget& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        label_(arena, from.label_) {}

NoKeyTarget::NoKeyTarget(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NoKeyTarget& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NoKeyTarget_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NoKeyTarget* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:DATA_MANAGER_FIXTURE.NoKeyTarget)
}
PROTOBUF_NDEBUG_INLINE NoKeyTarget::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        label_(arena) {}

inline void NoKeyTarget::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NoKeyTarget::~NoKeyTarget() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_FIXTURE.NoKeyTarget)
  SharedDtor(*this);
}
inline void NoKeyTarget::SharedDtor(MessageLite& self) {
  NoKeyTarget& this_ = static_cast<NoKeyTarget&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NoKeyTarget::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NoKeyTarget(arena);
}
constexpr auto NoKeyTarget::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NoKeyTarget),
                                            alignof(NoKeyTarget));
}
constexpr auto NoKeyTarget::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NoKeyTarget_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &NoKeyTarget::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NoKeyTarget>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NoKeyTarget::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NoKeyTarget>(), &NoKeyTarget::ByteSizeLong,
              &NoKeyTarget::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NoKeyTarget, _impl_._cached_size_),
          false,
      },
      &NoKeyTarget::kDescriptorMethods,
      &descriptor_table_KeyTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NoKeyTarget_class_data_ =
        NoKeyTarget::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NoKeyTarget::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NoKeyTarget_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NoKeyTarget_class_data_.tc_table);
  return NoKeyTarget_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 46, 2>
NoKeyTarget::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NoKeyTarget, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NoKeyTarget_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_FIXTURE::NoKeyTarget>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string label = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NoKeyTarget, _impl_.label_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string label = 1;
    {PROTOBUF_FIELD_OFFSET(NoKeyTarget, _impl_.label_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\5\0\0\0\0\0\0"
    "DATA_MANAGER_FIXTURE.NoKeyTarget"
    "label"
  }},
};
PROTOBUF_NOINLINE void NoKeyTarget::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_FIXTURE.NoKeyTarget)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.label_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NoKeyTarget::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NoKeyTarget& this_ = static_cast<const NoKeyTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NoKeyTarget::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NoKeyTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_FIXTURE.NoKeyTarget)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string label = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_label().empty()) {
      const ::std::string& _s = this_._internal_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_FIXTURE.NoKeyTarget.label");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_FIXTURE.NoKeyTarget)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NoKeyTarget::ByteSizeLong(const MessageLite& base) {
  const NoKeyTarget& this_ = static_cast<const NoKeyTarget&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NoKeyTarget::ByteSizeLong() const {
  const NoKeyTarget& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_FIXTURE.NoKeyTarget)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string label = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_label());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NoKeyTarget::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NoKeyTarget*>(&to_msg);
  auto& from = static_cast<const NoKeyTarget&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_FIXTURE.NoKeyTarget)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_label().empty()) {
      _this->_internal_set_label(from._internal_label());
    } else {
      if (_this->_impl_.label_.IsDefault()) {
        _this->_internal_set_label("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NoKeyTarget::CopyFrom(const NoKeyTarget& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_FIXTURE.NoKeyTarget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NoKeyTarget::InternalSwap(NoKeyTarget* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
}

::google::protobuf::Metadata NoKeyTarget::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_FIXTURE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_KeyTable_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
