// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GameItemTable.proto
// Protobuf C++ Version: 7.34.1

#include "GameItemTable.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace DATA_MANAGER_TABLE {

inline constexpr GameItemTypeDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        typename__(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iconpath_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        itemtype_{static_cast< ::DATA_MANAGER_TABLE::ItemType >(0)},
        istradable_{false} {}

template <typename>
constexpr GameItemTypeDef::GameItemTypeDef(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GameItemTypeDef_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct GameItemTypeDefDefaultTypeInternal {
  constexpr GameItemTypeDefDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameItemTypeDefDefaultTypeInternal() {}
  union {
    GameItemTypeDef _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameItemTypeDefDefaultTypeInternal _GameItemTypeDef_default_instance_;

inline constexpr GameItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        descriptions_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        itemtype_{nullptr},
        itemid_{0},
        rarity_{static_cast< ::DATA_MANAGER_TABLE::GradeType >(0)},
        maxstack_{0},
        price_{0} {}

template <typename>
constexpr GameItem::GameItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GameItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct GameItemDefaultTypeInternal {
  constexpr GameItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameItemDefaultTypeInternal() {}
  union {
    GameItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameItemDefaultTypeInternal _GameItem_default_instance_;
}  // namespace DATA_MANAGER_TABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_GameItemTable_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_GameItemTable_2eproto = nullptr;
const ::uint32_t
    TableStruct_GameItemTable_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItemTypeDef, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItemTypeDef, _impl_.itemtype_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItemTypeDef, _impl_.typename__),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItemTypeDef, _impl_.istradable_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItemTypeDef, _impl_.iconpath_),
        2,
        0,
        3,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.itemid_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.itemtype_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.rarity_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.maxstack_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::GameItem, _impl_.descriptions_),
        3,
        0,
        2,
        4,
        5,
        6,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::DATA_MANAGER_TABLE::GameItemTypeDef)},
        {11, sizeof(::DATA_MANAGER_TABLE::GameItem)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::DATA_MANAGER_TABLE::_GameItemTypeDef_default_instance_._instance,
    &::DATA_MANAGER_TABLE::_GameItem_default_instance_._instance,
};
const char descriptor_table_protodef_GameItemTable_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023GameItemTable.proto\022\022DATA_MANAGER_TABL"
    "E\032\024CommonEnumType.proto\032\022ItemEnumType.pr"
    "oto\"y\n\017GameItemTypeDef\022.\n\010itemType\030\001 \001(\016"
    "2\034.DATA_MANAGER_TABLE.ItemType\022\020\n\010typeNa"
    "me\030\002 \001(\t\022\022\n\nisTradable\030\003 \001(\010\022\020\n\010iconPath"
    "\030\004 \001(\t\"\305\001\n\010GameItem\022\016\n\006itemId\030\001 \001(\005\022\014\n\004n"
    "ame\030\002 \001(\t\0225\n\010itemType\030\003 \001(\0132#.DATA_MANAG"
    "ER_TABLE.GameItemTypeDef\022-\n\006rarity\030\004 \001(\016"
    "2\035.DATA_MANAGER_TABLE.GradeType\022\020\n\010maxSt"
    "ack\030\005 \001(\005\022\r\n\005price\030\006 \001(\005\022\024\n\014descriptions"
    "\030\007 \001(\tB\026Z\024./DATA_MANAGER_TABLEb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_GameItemTable_2eproto_deps[2] = {
        &::descriptor_table_CommonEnumType_2eproto,
        &::descriptor_table_ItemEnumType_2eproto,
};
static ::absl::once_flag descriptor_table_GameItemTable_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_GameItemTable_2eproto = {
    false,
    false,
    438,
    descriptor_table_protodef_GameItemTable_2eproto,
    "GameItemTable.proto",
    &descriptor_table_GameItemTable_2eproto_once,
    descriptor_table_GameItemTable_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_GameItemTable_2eproto::offsets,
    file_level_enum_descriptors_GameItemTable_2eproto,
    file_level_service_descriptors_GameItemTable_2eproto,
};
namespace DATA_MANAGER_TABLE {
// ===================================================================

class GameItemTypeDef::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GameItemTypeDef>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_._has_bits_);
};

GameItemTypeDef::GameItemTypeDef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GameItemTypeDef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_TABLE.GameItemTypeDef)
}
PROTOBUF_NDEBUG_INLINE GameItemTypeDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::DATA_MANAGER_TABLE::GameItemTypeDef& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        typename__(arena, from.typename__),
        iconpath_(arena, from.iconpath_) {}

GameItemTypeDef::GameItemTypeDef(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GameItemTypeDef& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GameItemTypeDef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GameItemTypeDef* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, itemtype_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, itemtype_),
           offsetof(Impl_, istradable_) -
               offsetof(Impl_, itemtype_) +
               sizeof(Impl_::istradable_));

  // @@protoc_insertion_point(copy_constructor:DATA_MANAGER_TABLE.GameItemTypeDef)
}
PROTOBUF_NDEBUG_INLINE GameItemTypeDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        typename__(arena),
        iconpath_(arena) {}

inline void GameItemTypeDef::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, itemtype_),
           0,
           offsetof(Impl_, istradable_) -
               offsetof(Impl_, itemtype_) +
               sizeof(Impl_::istradable_));
}
GameItemTypeDef::~GameItemTypeDef() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_TABLE.GameItemTypeDef)
  SharedDtor(*this);
}
inline void GameItemTypeDef::SharedDtor(MessageLite& self) {
  GameItemTypeDef& this_ = static_cast<GameItemTypeDef&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.typename__.Destroy();
  this_._impl_.iconpath_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GameItemTypeDef::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GameItemTypeDef(arena);
}
constexpr auto GameItemTypeDef::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GameItemTypeDef),
                                            alignof(GameItemTypeDef));
}
constexpr auto GameItemTypeDef::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GameItemTypeDef_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &GameItemTypeDef::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GameItemTypeDef>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GameItemTypeDef::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GameItemTypeDef>(), &GameItemTypeDef::ByteSizeLong,
              &GameItemTypeDef::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_._cached_size_),
          false,
      },
      &GameItemTypeDef::kDescriptorMethods,
      &descriptor_table_GameItemTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GameItemTypeDef_class_data_ =
        GameItemTypeDef::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GameItemTypeDef::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GameItemTypeDef_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GameItemTypeDef_class_data_.tc_table);
  return GameItemTypeDef_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 59, 2>
GameItemTypeDef::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GameItemTypeDef_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_TABLE::GameItemTypeDef>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string iconPath = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.iconpath_)}},
    // .DATA_MANAGER_TABLE.ItemType itemType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameItemTypeDef, _impl_.itemtype_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.itemtype_)}},
    // string typeName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.typename__)}},
    // bool isTradable = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(GameItemTypeDef, _impl_.istradable_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.istradable_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .DATA_MANAGER_TABLE.ItemType itemType = 1;
    {PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.itemtype_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string typeName = 2;
    {PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.typename__), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool isTradable = 3;
    {PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.istradable_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string iconPath = 4;
    {PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.iconpath_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\0\10\0\10\0\0\0"
    "DATA_MANAGER_TABLE.GameItemTypeDef"
    "typeName"
    "iconPath"
  }},
};
PROTOBUF_NOINLINE void GameItemTypeDef::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_TABLE.GameItemTypeDef)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.typename__.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.iconpath_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.itemtype_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.istradable_) -
        reinterpret_cast<char*>(&_impl_.itemtype_)) + sizeof(_impl_.istradable_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GameItemTypeDef::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GameItemTypeDef& this_ = static_cast<const GameItemTypeDef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GameItemTypeDef::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GameItemTypeDef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_TABLE.GameItemTypeDef)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .DATA_MANAGER_TABLE.ItemType itemType = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_itemtype() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_itemtype(), target);
    }
  }

  // string typeName = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_typename_().empty()) {
      const ::std::string& _s = this_._internal_typename_();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_TABLE.GameItemTypeDef.typeName");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bool isTradable = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_istradable() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_istradable(), target);
    }
  }

  // string iconPath = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_iconpath().empty()) {
      const ::std::string& _s = this_._internal_iconpath();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_TABLE.GameItemTypeDef.iconPath");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_TABLE.GameItemTypeDef)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GameItemTypeDef::ByteSizeLong(const MessageLite& base) {
  const GameItemTypeDef& this_ = static_cast<const GameItemTypeDef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GameItemTypeDef::ByteSizeLong() const {
  const GameItemTypeDef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_TABLE.GameItemTypeDef)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string typeName = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_typename_().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_typename_());
      }
    }
    // string iconPath = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_iconpath().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_iconpath());
      }
    }
    // .DATA_MANAGER_TABLE.ItemType itemType = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_itemtype() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_itemtype());
      }
    }
    // bool isTradable = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_istradable() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GameItemTypeDef::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GameItemTypeDef*>(&to_msg);
  auto& from = static_cast<const GameItemTypeDef&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_TABLE.GameItemTypeDef)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_typename_().empty()) {
        _this->_internal_set_typename_(from._internal_typename_());
      } else {
        if (_this->_impl_.typename__.IsDefault()) {
          _this->_internal_set_typename_("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_iconpath().empty()) {
        _this->_internal_set_iconpath(from._internal_iconpath());
      } else {
        if (_this->_impl_.iconpath_.IsDefault()) {
          _this->_internal_set_iconpath("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_itemtype() != 0) {
        _this->_impl_.itemtype_ = from._impl_.itemtype_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_istradable() != 0) {
        _this->_impl_.istradable_ = from._impl_.istradable_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GameItemTypeDef::CopyFrom(const GameItemTypeDef& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_TABLE.GameItemTypeDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GameItemTypeDef::InternalSwap(GameItemTypeDef* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.typename__, &other->_impl_.typename__, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.iconpath_, &other->_impl_.iconpath_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.istradable_)
      + sizeof(GameItemTypeDef::_impl_.istradable_)
      - PROTOBUF_FIELD_OFFSET(GameItemTypeDef, _impl_.itemtype_)>(
          reinterpret_cast<char*>(&_impl_.itemtype_),
          reinterpret_cast<char*>(&other->_impl_.itemtype_));
}

::google::protobuf::Metadata GameItemTypeDef::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GameItem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GameItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GameItem, _impl_._has_bits_);
};

GameItem::GameItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GameItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_TABLE.GameItem)
}
PROTOBUF_NDEBUG_INLINE GameItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::DATA_MANAGER_TABLE::GameItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        descriptions_(arena, from.descriptions_) {}

GameItem::GameItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GameItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GameItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GameItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.itemtype_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.itemtype_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, itemid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, itemid_),
           offsetof(Impl_, price_) -
               offsetof(Impl_, itemid_) +
               sizeof(Impl_::price_));

  // @@protoc_insertion_point(copy_constructor:DATA_MANAGER_TABLE.GameItem)
}
PROTOBUF_NDEBUG_INLINE GameItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena),
        descriptions_(arena) {}

inline void GameItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, itemtype_),
           0,
           offsetof(Impl_, price_) -
               offsetof(Impl_, itemtype_) +
               sizeof(Impl_::price_));
}
GameItem::~GameItem() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_TABLE.GameItem)
  SharedDtor(*this);
}
inline void GameItem::SharedDtor(MessageLite& self) {
  GameItem& this_ = static_cast<GameItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.descriptions_.Destroy();
  delete this_._impl_.itemtype_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GameItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GameItem(arena);
}
constexpr auto GameItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GameItem),
                                            alignof(GameItem));
}
constexpr auto GameItem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GameItem_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &GameItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GameItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GameItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GameItem>(), &GameItem::ByteSizeLong,
              &GameItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GameItem, _impl_._cached_size_),
          false,
      },
      &GameItem::kDescriptorMethods,
      &descriptor_table_GameItemTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GameItem_class_data_ =
        GameItem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GameItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GameItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GameItem_class_data_.tc_table);
  return GameItem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 1, 52, 2>
GameItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GameItem, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GameItem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_TABLE::GameItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 itemId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameItem, _impl_.itemid_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.itemid_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.name_)}},
    // .DATA_MANAGER_TABLE.GameItemTypeDef itemType = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.itemtype_)}},
    // .DATA_MANAGER_TABLE.GradeType rarity = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameItem, _impl_.rarity_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.rarity_)}},
    // int32 maxStack = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameItem, _impl_.maxstack_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.maxstack_)}},
    // int32 price = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameItem, _impl_.price_), 6>(),
     {48, 6, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.price_)}},
    // string descriptions = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 1, 0,
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.descriptions_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 itemId = 1;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.itemid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .DATA_MANAGER_TABLE.GameItemTypeDef itemType = 3;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.itemtype_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .DATA_MANAGER_TABLE.GradeType rarity = 4;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.rarity_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int32 maxStack = 5;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.maxstack_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 price = 6;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.price_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string descriptions = 7;
    {PROTOBUF_FIELD_OFFSET(GameItem, _impl_.descriptions_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::DATA_MANAGER_TABLE::GameItemTypeDef>()},
  }},
  {{
    "\33\0\4\0\0\0\0\14"
    "DATA_MANAGER_TABLE.GameItem"
    "name"
    "descriptions"
  }},
};
PROTOBUF_NOINLINE void GameItem::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_TABLE.GameItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.descriptions_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.itemtype_ != nullptr);
      _impl_.itemtype_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000078U)) {
    ::memset(&_impl_.itemid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.price_) -
        reinterpret_cast<char*>(&_impl_.itemid_)) + sizeof(_impl_.price_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GameItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GameItem& this_ = static_cast<const GameItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GameItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GameItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_TABLE.GameItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 itemId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_itemid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_itemid(), target);
    }
  }

  // string name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_TABLE.GameItem.name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // .DATA_MANAGER_TABLE.GameItemTypeDef itemType = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.itemtype_, this_._impl_.itemtype_->GetCachedSize(), target,
        stream);
  }

  // .DATA_MANAGER_TABLE.GradeType rarity = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_rarity() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_rarity(), target);
    }
  }

  // int32 maxStack = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_maxstack() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_maxstack(), target);
    }
  }

  // int32 price = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_price() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_price(), target);
    }
  }

  // string descriptions = 7;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_descriptions().empty()) {
      const ::std::string& _s = this_._internal_descriptions();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DATA_MANAGER_TABLE.GameItem.descriptions");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_TABLE.GameItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GameItem::ByteSizeLong(const MessageLite& base) {
  const GameItem& this_ = static_cast<const GameItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GameItem::ByteSizeLong() const {
  const GameItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_TABLE.GameItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string descriptions = 7;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_descriptions().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_descriptions());
      }
    }
    // .DATA_MANAGER_TABLE.GameItemTypeDef itemType = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.itemtype_);
    }
    // int32 itemId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_itemid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_itemid());
      }
    }
    // .DATA_MANAGER_TABLE.GradeType rarity = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_rarity() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_rarity());
      }
    }
    // int32 maxStack = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_maxstack() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_maxstack());
      }
    }
    // int32 price = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_price() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_price());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GameItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GameItem*>(&to_msg);
  auto& from = static_cast<const GameItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_TABLE.GameItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_descriptions().empty()) {
        _this->_internal_set_descriptions(from._internal_descriptions());
      } else {
        if (_this->_impl_.descriptions_.IsDefault()) {
          _this->_internal_set_descriptions("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.itemtype_ != nullptr);
      if (_this->_impl_.itemtype_ == nullptr) {
        _this->_impl_.itemtype_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.itemtype_);
      } else {
        _this->_impl_.itemtype_->MergeFrom(*from._impl_.itemtype_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_itemid() != 0) {
        _this->_impl_.itemid_ = from._impl_.itemid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_rarity() != 0) {
        _this->_impl_.rarity_ = from._impl_.rarity_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_maxstack() != 0) {
        _this->_impl_.maxstack_ = from._impl_.maxstack_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_price() != 0) {
        _this->_impl_.price_ = from._impl_.price_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GameItem::CopyFrom(const GameItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_TABLE.GameItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GameItem::InternalSwap(GameItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.descriptions_, &other->_impl_.descriptions_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameItem, _impl_.price_)
      + sizeof(GameItem::_impl_.price_)
      - PROTOBUF_FIELD_OFFSET(GameItem, _impl_.itemtype_)>(
          reinterpret_cast<char*>(&_impl_.itemtype_),
          reinterpret_cast<char*>(&other->_impl_.itemtype_));
}

::google::protobuf::Metadata GameItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_TABLE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_GameItemTable_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
