// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ItemEnumType.proto
// Protobuf C++ Version: 7.34.1

#ifndef ItemEnumType_2eproto_2epb_2eh
#define ItemEnumType_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ItemEnumType_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ItemEnumType_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ItemEnumType_2eproto;
}  // extern "C"
namespace DATA_MANAGER_TABLE {
enum ItemType : int;
extern const uint32_t ItemType_internal_data_[];
}  // namespace DATA_MANAGER_TABLE
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::DATA_MANAGER_TABLE::ItemType_internal_data_>
    internal::EnumTraitsImpl::value<::DATA_MANAGER_TABLE::ItemType>;
}  // namespace protobuf
}  // namespace google

namespace DATA_MANAGER_TABLE {
enum ItemType : int {
  ItemType_NONE = 0,
  ItemType_EQUIPMENT = 1,
  ItemType_CONSUMABLE = 2,
  ItemType_MATERIAL = 3,
  ItemType_QUEST = 4,
  ItemType_MAX = 5,
  ItemType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ItemType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ItemType_internal_data_[];
inline constexpr ItemType ItemType_MIN =
    static_cast<ItemType>(0);
inline constexpr ItemType ItemType_MAX =
    static_cast<ItemType>(5);
[[nodiscard]] inline bool ItemType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int ItemType_ARRAYSIZE = 5 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
ItemType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(ItemType) {
  return ItemType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& ItemType_Name(T value) {
  static_assert(::std::is_same<T, ItemType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ItemType_Name().");
  return ItemType_Name(static_cast<ItemType>(value));
}
template <>
[[nodiscard]] inline const ::std::string& ItemType_Name(ItemType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ItemType_descriptor, 0, 5>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool ItemType_Parse(
    ::absl::string_view name, ItemType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ItemType>(ItemType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_TABLE


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::DATA_MANAGER_TABLE::ItemType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::DATA_MANAGER_TABLE::ItemType>() {
  return ::DATA_MANAGER_TABLE::ItemType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // ItemEnumType_2eproto_2epb_2eh
