// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MonsterTable.proto
// Protobuf C++ Version: 7.34.1

#ifndef MonsterTable_2eproto_2epb_2eh
#define MonsterTable_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "RewardItemTable.pb.h"
#include "StringTable.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MonsterTable_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MonsterTable_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_MonsterTable_2eproto;
}  // extern "C"
namespace DATA_MANAGER_TABLE {
class Monster;
struct MonsterDefaultTypeInternal;
extern MonsterDefaultTypeInternal _Monster_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Monster_class_data_;
class MonsterRace;
struct MonsterRaceDefaultTypeInternal;
extern MonsterRaceDefaultTypeInternal _MonsterRace_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MonsterRace_class_data_;
}  // namespace DATA_MANAGER_TABLE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace DATA_MANAGER_TABLE {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Monster final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DATA_MANAGER_TABLE.Monster) */ {
 public:
  inline Monster() : Monster(nullptr) {}
  ~Monster() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Monster* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Monster));
  }
#endif

  template <typename = void>
  explicit constexpr Monster(::google::protobuf::internal::ConstantInitialized);

  inline Monster(const Monster& from) : Monster(nullptr, from) {}
  inline Monster(Monster&& from) noexcept
      : Monster(nullptr, ::std::move(from)) {}
  inline Monster& operator=(const Monster& from) {
    CopyFrom(from);
    return *this;
  }
  inline Monster& operator=(Monster&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Monster& default_instance() {
    return *reinterpret_cast<const Monster*>(
        &_Monster_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Monster& a, Monster& b) { a.Swap(&b); }
  inline void Swap(Monster* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Monster* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Monster* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Monster>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Monster& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Monster& from) { Monster::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Monster* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DATA_MANAGER_TABLE.Monster"; }

  explicit Monster(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Monster(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Monster& from);
  Monster(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Monster&& from) noexcept
      : Monster(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kRewardGroupIdFieldNumber = 7,
    kMonsterIdFieldNumber = 1,
    kHpFieldNumber = 3,
    kAtkFieldNumber = 4,
    kDefFieldNumber = 5,
    kMoveSpeedFieldNumber = 6,
  };
  // .DATA_MANAGER_TABLE.StringData name = 2;
  [[nodiscard]] bool has_name()
      const;
  void clear_name() ;
  [[nodiscard]] const ::DATA_MANAGER_TABLE::StringData& name() const;
  [[nodiscard]] ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE release_name();
  ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NONNULL mutable_name();
  void set_allocated_name(::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_name(::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE value);
  ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE unsafe_arena_release_name();

  private:
  const ::DATA_MANAGER_TABLE::StringData& _internal_name() const;
  ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .DATA_MANAGER_TABLE.RewardItemGroup RewardGroupId = 7;
  [[nodiscard]] bool has_rewardgroupid()
      const;
  void clear_rewardgroupid() ;
  [[nodiscard]] const ::DATA_MANAGER_TABLE::RewardItemGroup& rewardgroupid() const;
  [[nodiscard]] ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE release_rewardgroupid();
  ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NONNULL mutable_rewardgroupid();
  void set_allocated_rewardgroupid(::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_rewardgroupid(::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE value);
  ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE unsafe_arena_release_rewardgroupid();

  private:
  const ::DATA_MANAGER_TABLE::RewardItemGroup& _internal_rewardgroupid() const;
  ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NONNULL _internal_mutable_rewardgroupid();

  public:
  // int32 monsterId = 1;
  void clear_monsterid() ;
  [[nodiscard]] ::int32_t monsterid() const;
  void set_monsterid(::int32_t value);

  private:
  ::int32_t _internal_monsterid() const;
  void _internal_set_monsterid(::int32_t value);

  public:
  // int32 hp = 3;
  void clear_hp() ;
  [[nodiscard]] ::int32_t hp() const;
  void set_hp(::int32_t value);

  private:
  ::int32_t _internal_hp() const;
  void _internal_set_hp(::int32_t value);

  public:
  // int32 atk = 4;
  void clear_atk() ;
  [[nodiscard]] ::int32_t atk() const;
  void set_atk(::int32_t value);

  private:
  ::int32_t _internal_atk() const;
  void _internal_set_atk(::int32_t value);

  public:
  // int32 def = 5;
  void clear_def() ;
  [[nodiscard]] ::int32_t def() const;
  void set_def(::int32_t value);

  private:
  ::int32_t _internal_def() const;
  void _internal_set_def(::int32_t value);

  public:
  // float moveSpeed = 6;
  void clear_movespeed() ;
  [[nodiscard]] float movespeed() const;
  void set_movespeed(float value);

  private:
  float _internal_movespeed() const;
  void _internal_set_movespeed(float value);

  public:
  // @@protoc_insertion_point(class_scope:DATA_MANAGER_TABLE.Monster)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Monster& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE name_;
    ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE rewardgroupid_;
    ::int32_t monsterid_;
    ::int32_t hp_;
    ::int32_t atk_;
    ::int32_t def_;
    float movespeed_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MonsterTable_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Monster_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MonsterRace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DATA_MANAGER_TABLE.MonsterRace) */ {
 public:
  inline MonsterRace() : MonsterRace(nullptr) {}
  ~MonsterRace() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MonsterRace* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MonsterRace));
  }
#endif

  template <typename = void>
  explicit constexpr MonsterRace(::google::protobuf::internal::ConstantInitialized);

  inline MonsterRace(const MonsterRace& from) : MonsterRace(nullptr, from) {}
  inline MonsterRace(MonsterRace&& from) noexcept
      : MonsterRace(nullptr, ::std::move(from)) {}
  inline MonsterRace& operator=(const MonsterRace& from) {
    CopyFrom(from);
    return *this;
  }
  inline MonsterRace& operator=(MonsterRace&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MonsterRace& default_instance() {
    return *reinterpret_cast<const MonsterRace*>(
        &_MonsterRace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MonsterRace& a, MonsterRace& b) { a.Swap(&b); }
  inline void Swap(MonsterRace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MonsterRace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MonsterRace* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MonsterRace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MonsterRace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MonsterRace& from) { MonsterRace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MonsterRace* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DATA_MANAGER_TABLE.MonsterRace"; }

  explicit MonsterRace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MonsterRace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MonsterRace& from);
  MonsterRace(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MonsterRace&& from) noexcept
      : MonsterRace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMonsterIDFieldNumber = 2,
    kGroupIDFieldNumber = 1,
    kMemoFieldNumber = 3,
  };
  // .DATA_MANAGER_TABLE.Monster MonsterID = 2;
  [[nodiscard]] bool has_monsterid()
      const;
  void clear_monsterid() ;
  [[nodiscard]] const ::DATA_MANAGER_TABLE::Monster& monsterid() const;
  [[nodiscard]] ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE release_monsterid();
  ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NONNULL mutable_monsterid();
  void set_allocated_monsterid(::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_monsterid(::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE value);
  ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE unsafe_arena_release_monsterid();

  private:
  const ::DATA_MANAGER_TABLE::Monster& _internal_monsterid() const;
  ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NONNULL _internal_mutable_monsterid();

  public:
  // int32 GroupID = 1;
  void clear_groupid() ;
  [[nodiscard]] ::int32_t groupid() const;
  void set_groupid(::int32_t value);

  private:
  ::int32_t _internal_groupid() const;
  void _internal_set_groupid(::int32_t value);

  public:
  // int32 Memo = 3;
  void clear_memo() ;
  [[nodiscard]] ::int32_t memo() const;
  void set_memo(::int32_t value);

  private:
  ::int32_t _internal_memo() const;
  void _internal_set_memo(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DATA_MANAGER_TABLE.MonsterRace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MonsterRace& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE monsterid_;
    ::int32_t groupid_;
    ::int32_t memo_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MonsterTable_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MonsterRace_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MonsterRace

// int32 GroupID = 1;
inline void MonsterRace::clear_groupid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.groupid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t MonsterRace::groupid() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.MonsterRace.GroupID)
  return _internal_groupid();
}
inline void MonsterRace::set_groupid(::int32_t value) {
  _internal_set_groupid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.MonsterRace.GroupID)
}
inline ::int32_t MonsterRace::_internal_groupid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.groupid_;
}
inline void MonsterRace::_internal_set_groupid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.groupid_ = value;
}

// .DATA_MANAGER_TABLE.Monster MonsterID = 2;
inline bool MonsterRace::has_monsterid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.monsterid_ != nullptr);
  return value;
}
inline void MonsterRace::clear_monsterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.monsterid_ != nullptr) _impl_.monsterid_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::DATA_MANAGER_TABLE::Monster& MonsterRace::_internal_monsterid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::DATA_MANAGER_TABLE::Monster* p = _impl_.monsterid_;
  return p != nullptr ? *p : reinterpret_cast<const ::DATA_MANAGER_TABLE::Monster&>(::DATA_MANAGER_TABLE::_Monster_default_instance_);
}
inline const ::DATA_MANAGER_TABLE::Monster& MonsterRace::monsterid() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.MonsterRace.MonsterID)
  return _internal_monsterid();
}
inline void MonsterRace::unsafe_arena_set_allocated_monsterid(
    ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.monsterid_);
  }
  _impl_.monsterid_ = reinterpret_cast<::DATA_MANAGER_TABLE::Monster*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DATA_MANAGER_TABLE.MonsterRace.MonsterID)
}
inline ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE MonsterRace::release_monsterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::DATA_MANAGER_TABLE::Monster* released = _impl_.monsterid_;
  _impl_.monsterid_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE MonsterRace::unsafe_arena_release_monsterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DATA_MANAGER_TABLE.MonsterRace.MonsterID)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::DATA_MANAGER_TABLE::Monster* temp = _impl_.monsterid_;
  _impl_.monsterid_ = nullptr;
  return temp;
}
inline ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NONNULL MonsterRace::_internal_mutable_monsterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.monsterid_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::DATA_MANAGER_TABLE::Monster>(GetArena());
    _impl_.monsterid_ = reinterpret_cast<::DATA_MANAGER_TABLE::Monster*>(p);
  }
  return _impl_.monsterid_;
}
inline ::DATA_MANAGER_TABLE::Monster* PROTOBUF_NONNULL MonsterRace::mutable_monsterid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::DATA_MANAGER_TABLE::Monster* _msg = _internal_mutable_monsterid();
  // @@protoc_insertion_point(field_mutable:DATA_MANAGER_TABLE.MonsterRace.MonsterID)
  return _msg;
}
inline void MonsterRace::set_allocated_monsterid(::DATA_MANAGER_TABLE::Monster* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.monsterid_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.monsterid_ = reinterpret_cast<::DATA_MANAGER_TABLE::Monster*>(value);
  // @@protoc_insertion_point(field_set_allocated:DATA_MANAGER_TABLE.MonsterRace.MonsterID)
}

// int32 Memo = 3;
inline void MonsterRace::clear_memo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memo_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t MonsterRace::memo() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.MonsterRace.Memo)
  return _internal_memo();
}
inline void MonsterRace::set_memo(::int32_t value) {
  _internal_set_memo(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.MonsterRace.Memo)
}
inline ::int32_t MonsterRace::_internal_memo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.memo_;
}
inline void MonsterRace::_internal_set_memo(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memo_ = value;
}

// -------------------------------------------------------------------

// Monster

// int32 monsterId = 1;
inline void Monster::clear_monsterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.monsterid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Monster::monsterid() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.monsterId)
  return _internal_monsterid();
}
inline void Monster::set_monsterid(::int32_t value) {
  _internal_set_monsterid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.Monster.monsterId)
}
inline ::int32_t Monster::_internal_monsterid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.monsterid_;
}
inline void Monster::_internal_set_monsterid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.monsterid_ = value;
}

// .DATA_MANAGER_TABLE.StringData name = 2;
inline bool Monster::has_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.name_ != nullptr);
  return value;
}
inline const ::DATA_MANAGER_TABLE::StringData& Monster::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::DATA_MANAGER_TABLE::StringData* p = _impl_.name_;
  return p != nullptr ? *p : reinterpret_cast<const ::DATA_MANAGER_TABLE::StringData&>(::DATA_MANAGER_TABLE::_StringData_default_instance_);
}
inline const ::DATA_MANAGER_TABLE::StringData& Monster::name() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.name)
  return _internal_name();
}
inline void Monster::unsafe_arena_set_allocated_name(
    ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.name_);
  }
  _impl_.name_ = reinterpret_cast<::DATA_MANAGER_TABLE::StringData*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DATA_MANAGER_TABLE.Monster.name)
}
inline ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE Monster::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::DATA_MANAGER_TABLE::StringData* released = _impl_.name_;
  _impl_.name_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE Monster::unsafe_arena_release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DATA_MANAGER_TABLE.Monster.name)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::DATA_MANAGER_TABLE::StringData* temp = _impl_.name_;
  _impl_.name_ = nullptr;
  return temp;
}
inline ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NONNULL Monster::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.name_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::DATA_MANAGER_TABLE::StringData>(GetArena());
    _impl_.name_ = reinterpret_cast<::DATA_MANAGER_TABLE::StringData*>(p);
  }
  return _impl_.name_;
}
inline ::DATA_MANAGER_TABLE::StringData* PROTOBUF_NONNULL Monster::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::DATA_MANAGER_TABLE::StringData* _msg = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:DATA_MANAGER_TABLE.Monster.name)
  return _msg;
}
inline void Monster::set_allocated_name(::DATA_MANAGER_TABLE::StringData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.name_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.name_ = reinterpret_cast<::DATA_MANAGER_TABLE::StringData*>(value);
  // @@protoc_insertion_point(field_set_allocated:DATA_MANAGER_TABLE.Monster.name)
}

// int32 hp = 3;
inline void Monster::clear_hp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t Monster::hp() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.hp)
  return _internal_hp();
}
inline void Monster::set_hp(::int32_t value) {
  _internal_set_hp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.Monster.hp)
}
inline ::int32_t Monster::_internal_hp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hp_;
}
inline void Monster::_internal_set_hp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hp_ = value;
}

// int32 atk = 4;
inline void Monster::clear_atk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.atk_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t Monster::atk() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.atk)
  return _internal_atk();
}
inline void Monster::set_atk(::int32_t value) {
  _internal_set_atk(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.Monster.atk)
}
inline ::int32_t Monster::_internal_atk() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.atk_;
}
inline void Monster::_internal_set_atk(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.atk_ = value;
}

// int32 def = 5;
inline void Monster::clear_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.def_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t Monster::def() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.def)
  return _internal_def();
}
inline void Monster::set_def(::int32_t value) {
  _internal_set_def(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.Monster.def)
}
inline ::int32_t Monster::_internal_def() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.def_;
}
inline void Monster::_internal_set_def(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.def_ = value;
}

// float moveSpeed = 6;
inline void Monster::clear_movespeed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.movespeed_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline float Monster::movespeed() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.moveSpeed)
  return _internal_movespeed();
}
inline void Monster::set_movespeed(float value) {
  _internal_set_movespeed(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.Monster.moveSpeed)
}
inline float Monster::_internal_movespeed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.movespeed_;
}
inline void Monster::_internal_set_movespeed(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.movespeed_ = value;
}

// .DATA_MANAGER_TABLE.RewardItemGroup RewardGroupId = 7;
inline bool Monster::has_rewardgroupid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.rewardgroupid_ != nullptr);
  return value;
}
inline const ::DATA_MANAGER_TABLE::RewardItemGroup& Monster::_internal_rewardgroupid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::DATA_MANAGER_TABLE::RewardItemGroup* p = _impl_.rewardgroupid_;
  return p != nullptr ? *p : reinterpret_cast<const ::DATA_MANAGER_TABLE::RewardItemGroup&>(::DATA_MANAGER_TABLE::_RewardItemGroup_default_instance_);
}
inline const ::DATA_MANAGER_TABLE::RewardItemGroup& Monster::rewardgroupid() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.Monster.RewardGroupId)
  return _internal_rewardgroupid();
}
inline void Monster::unsafe_arena_set_allocated_rewardgroupid(
    ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.rewardgroupid_);
  }
  _impl_.rewardgroupid_ = reinterpret_cast<::DATA_MANAGER_TABLE::RewardItemGroup*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DATA_MANAGER_TABLE.Monster.RewardGroupId)
}
inline ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE Monster::release_rewardgroupid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::DATA_MANAGER_TABLE::RewardItemGroup* released = _impl_.rewardgroupid_;
  _impl_.rewardgroupid_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE Monster::unsafe_arena_release_rewardgroupid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DATA_MANAGER_TABLE.Monster.RewardGroupId)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::DATA_MANAGER_TABLE::RewardItemGroup* temp = _impl_.rewardgroupid_;
  _impl_.rewardgroupid_ = nullptr;
  return temp;
}
inline ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NONNULL Monster::_internal_mutable_rewardgroupid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rewardgroupid_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::DATA_MANAGER_TABLE::RewardItemGroup>(GetArena());
    _impl_.rewardgroupid_ = reinterpret_cast<::DATA_MANAGER_TABLE::RewardItemGroup*>(p);
  }
  return _impl_.rewardgroupid_;
}
inline ::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NONNULL Monster::mutable_rewardgroupid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::DATA_MANAGER_TABLE::RewardItemGroup* _msg = _internal_mutable_rewardgroupid();
  // @@protoc_insertion_point(field_mutable:DATA_MANAGER_TABLE.Monster.RewardGroupId)
  return _msg;
}
inline void Monster::set_allocated_rewardgroupid(::DATA_MANAGER_TABLE::RewardItemGroup* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.rewardgroupid_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.rewardgroupid_ = reinterpret_cast<::DATA_MANAGER_TABLE::RewardItemGroup*>(value);
  // @@protoc_insertion_point(field_set_allocated:DATA_MANAGER_TABLE.Monster.RewardGroupId)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_TABLE


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // MonsterTable_2eproto_2epb_2eh
