// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StringTable.proto
// Protobuf C++ Version: 7.34.1

#ifndef StringTable_2eproto_2epb_2eh
#define StringTable_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_StringTable_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_StringTable_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_StringTable_2eproto;
}  // extern "C"
namespace DATA_MANAGER_TABLE {
class StringData;
struct StringDataDefaultTypeInternal;
extern StringDataDefaultTypeInternal _StringData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StringData_class_data_;
}  // namespace DATA_MANAGER_TABLE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace DATA_MANAGER_TABLE {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED StringData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DATA_MANAGER_TABLE.StringData) */ {
 public:
  inline StringData() : StringData(nullptr) {}
  ~StringData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StringData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StringData));
  }
#endif

  template <typename = void>
  explicit constexpr StringData(::google::protobuf::internal::ConstantInitialized);

  inline StringData(const StringData& from) : StringData(nullptr, from) {}
  inline StringData(StringData&& from) noexcept
      : StringData(nullptr, ::std::move(from)) {}
  inline StringData& operator=(const StringData& from) {
    CopyFrom(from);
    return *this;
  }
  inline StringData& operator=(StringData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const StringData& default_instance() {
    return *reinterpret_cast<const StringData*>(
        &_StringData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StringData& a, StringData& b) { a.Swap(&b); }
  inline void Swap(StringData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StringData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] StringData* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StringData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StringData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StringData& from) { StringData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StringData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DATA_MANAGER_TABLE.StringData"; }

  explicit StringData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StringData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StringData& from);
  StringData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StringData&& from) noexcept
      : StringData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kKoFieldNumber = 2,
    kEnFieldNumber = 3,
  };
  // int32 Id = 1;
  void clear_id() ;
  [[nodiscard]] ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 ko = 2;
  void clear_ko() ;
  [[nodiscard]] ::int32_t ko() const;
  void set_ko(::int32_t value);

  private:
  ::int32_t _internal_ko() const;
  void _internal_set_ko(::int32_t value);

  public:
  // int32 en = 3;
  void clear_en() ;
  [[nodiscard]] ::int32_t en() const;
  void set_en(::int32_t value);

  private:
  ::int32_t _internal_en() const;
  void _internal_set_en(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DATA_MANAGER_TABLE.StringData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StringData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t id_;
    ::int32_t ko_;
    ::int32_t en_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_StringTable_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StringData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StringData

// int32 Id = 1;
inline void StringData::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t StringData::id() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.StringData.Id)
  return _internal_id();
}
inline void StringData::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.StringData.Id)
}
inline ::int32_t StringData::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void StringData::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// int32 ko = 2;
inline void StringData::clear_ko() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ko_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t StringData::ko() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.StringData.ko)
  return _internal_ko();
}
inline void StringData::set_ko(::int32_t value) {
  _internal_set_ko(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.StringData.ko)
}
inline ::int32_t StringData::_internal_ko() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ko_;
}
inline void StringData::_internal_set_ko(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ko_ = value;
}

// int32 en = 3;
inline void StringData::clear_en() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.en_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t StringData::en() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.StringData.en)
  return _internal_en();
}
inline void StringData::set_en(::int32_t value) {
  _internal_set_en(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.StringData.en)
}
inline ::int32_t StringData::_internal_en() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.en_;
}
inline void StringData::_internal_set_en(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.en_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_TABLE


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // StringTable_2eproto_2epb_2eh
