// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StringTable.proto
// Protobuf C++ Version: 7.34.1

#include "StringTable.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace DATA_MANAGER_TABLE {

inline constexpr StringData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0},
        ko_{0},
        en_{0} {}

template <typename>
constexpr StringData::StringData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(StringData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct StringDataDefaultTypeInternal {
  constexpr StringDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StringDataDefaultTypeInternal() {}
  union {
    StringData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StringDataDefaultTypeInternal _StringData_default_instance_;
}  // namespace DATA_MANAGER_TABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_StringTable_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_StringTable_2eproto = nullptr;
const ::uint32_t
    TableStruct_StringTable_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::StringData, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::StringData, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::StringData, _impl_.ko_),
        PROTOBUF_FIELD_OFFSET(::DATA_MANAGER_TABLE::StringData, _impl_.en_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::DATA_MANAGER_TABLE::StringData)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::DATA_MANAGER_TABLE::_StringData_default_instance_._instance,
};
const char descriptor_table_protodef_StringTable_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021StringTable.proto\022\022DATA_MANAGER_TABLE\""
    "0\n\nStringData\022\n\n\002Id\030\001 \001(\005\022\n\n\002ko\030\002 \001(\005\022\n\n"
    "\002en\030\003 \001(\005B\026Z\024./DATA_MANAGER_TABLEb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_StringTable_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_StringTable_2eproto = {
    false,
    false,
    121,
    descriptor_table_protodef_StringTable_2eproto,
    "StringTable.proto",
    &descriptor_table_StringTable_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_StringTable_2eproto::offsets,
    file_level_enum_descriptors_StringTable_2eproto,
    file_level_service_descriptors_StringTable_2eproto,
};
namespace DATA_MANAGER_TABLE {
// ===================================================================

class StringData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<StringData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StringData, _impl_._has_bits_);
};

StringData::StringData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StringData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DATA_MANAGER_TABLE.StringData)
}
StringData::StringData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StringData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StringData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE StringData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void StringData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, en_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::en_));
}
StringData::~StringData() {
  // @@protoc_insertion_point(destructor:DATA_MANAGER_TABLE.StringData)
  SharedDtor(*this);
}
inline void StringData::SharedDtor(MessageLite& self) {
  StringData& this_ = static_cast<StringData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL StringData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) StringData(arena);
}
constexpr auto StringData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StringData),
                                            alignof(StringData));
}
constexpr auto StringData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_StringData_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &StringData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<StringData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &StringData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<StringData>(), &StringData::ByteSizeLong,
              &StringData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(StringData, _impl_._cached_size_),
          false,
      },
      &StringData::kDescriptorMethods,
      &descriptor_table_StringTable_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull StringData_class_data_ =
        StringData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
StringData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&StringData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(StringData_class_data_.tc_table);
  return StringData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
StringData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StringData, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    StringData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DATA_MANAGER_TABLE::StringData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 Id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StringData, _impl_.id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(StringData, _impl_.id_)}},
    // int32 ko = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StringData, _impl_.ko_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(StringData, _impl_.ko_)}},
    // int32 en = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StringData, _impl_.en_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(StringData, _impl_.en_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 Id = 1;
    {PROTOBUF_FIELD_OFFSET(StringData, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 ko = 2;
    {PROTOBUF_FIELD_OFFSET(StringData, _impl_.ko_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 en = 3;
    {PROTOBUF_FIELD_OFFSET(StringData, _impl_.en_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void StringData::Clear() {
// @@protoc_insertion_point(message_clear_start:DATA_MANAGER_TABLE.StringData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.en_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.en_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL StringData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const StringData& this_ = static_cast<const StringData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL StringData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const StringData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:DATA_MANAGER_TABLE.StringData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 Id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // int32 ko = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_ko() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_ko(), target);
    }
  }

  // int32 en = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_en() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_en(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DATA_MANAGER_TABLE.StringData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t StringData::ByteSizeLong(const MessageLite& base) {
  const StringData& this_ = static_cast<const StringData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t StringData::ByteSizeLong() const {
  const StringData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DATA_MANAGER_TABLE.StringData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // int32 Id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // int32 ko = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_ko() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_ko());
      }
    }
    // int32 en = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_en() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_en());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void StringData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<StringData*>(&to_msg);
  auto& from = static_cast<const StringData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:DATA_MANAGER_TABLE.StringData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_ko() != 0) {
        _this->_impl_.ko_ = from._impl_.ko_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_en() != 0) {
        _this->_impl_.en_ = from._impl_.en_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void StringData::CopyFrom(const StringData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:DATA_MANAGER_TABLE.StringData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StringData::InternalSwap(StringData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StringData, _impl_.en_)
      + sizeof(StringData::_impl_.en_)
      - PROTOBUF_FIELD_OFFSET(StringData, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata StringData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_TABLE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_StringTable_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
