// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TestTable.proto
// Protobuf C++ Version: 7.34.1

#ifndef TestTable_2eproto_2epb_2eh
#define TestTable_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "TestEnumType.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_TestTable_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_TestTable_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_TestTable_2eproto;
}  // extern "C"
namespace DATA_MANAGER_TABLE {
class GoTest;
struct GoTestDefaultTypeInternal;
extern GoTestDefaultTypeInternal _GoTest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GoTest_class_data_;
}  // namespace DATA_MANAGER_TABLE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace DATA_MANAGER_TABLE {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED GoTest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DATA_MANAGER_TABLE.GoTest) */ {
 public:
  inline GoTest() : GoTest(nullptr) {}
  ~GoTest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GoTest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GoTest));
  }
#endif

  template <typename = void>
  explicit constexpr GoTest(::google::protobuf::internal::ConstantInitialized);

  inline GoTest(const GoTest& from) : GoTest(nullptr, from) {}
  inline GoTest(GoTest&& from) noexcept
      : GoTest(nullptr, ::std::move(from)) {}
  inline GoTest& operator=(const GoTest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GoTest& operator=(GoTest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const GoTest& default_instance() {
    return *reinterpret_cast<const GoTest*>(
        &_GoTest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GoTest& a, GoTest& b) { a.Swap(&b); }
  inline void Swap(GoTest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GoTest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] GoTest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GoTest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GoTest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GoTest& from) { GoTest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GoTest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DATA_MANAGER_TABLE.GoTest"; }

  explicit GoTest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GoTest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GoTest& from);
  GoTest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GoTest&& from) noexcept
      : GoTest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIDFieldNumber = 1,
    kTestColumnFieldNumber = 2,
    kTest23FieldNumber = 3,
    kTest45FieldNumber = 4,
  };
  // int32 ID = 1;
  void clear_id() ;
  [[nodiscard]] ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // .DATA_MANAGER_TABLE.TestType TestColumn = 2;
  void clear_testcolumn() ;
  [[nodiscard]] ::DATA_MANAGER_TABLE::TestType testcolumn() const;
  void set_testcolumn(::DATA_MANAGER_TABLE::TestType value);

  private:
  ::DATA_MANAGER_TABLE::TestType _internal_testcolumn() const;
  void _internal_set_testcolumn(::DATA_MANAGER_TABLE::TestType value);

  public:
  // int32 Test23 = 3;
  void clear_test23() ;
  [[nodiscard]] ::int32_t test23() const;
  void set_test23(::int32_t value);

  private:
  ::int32_t _internal_test23() const;
  void _internal_set_test23(::int32_t value);

  public:
  // int32 Test45 = 4;
  void clear_test45() ;
  [[nodiscard]] ::int32_t test45() const;
  void set_test45(::int32_t value);

  private:
  ::int32_t _internal_test45() const;
  void _internal_set_test45(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DATA_MANAGER_TABLE.GoTest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GoTest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t id_;
    int testcolumn_;
    ::int32_t test23_;
    ::int32_t test45_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TestTable_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GoTest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GoTest

// int32 ID = 1;
inline void GoTest::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t GoTest::id() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.GoTest.ID)
  return _internal_id();
}
inline void GoTest::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.GoTest.ID)
}
inline ::int32_t GoTest::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void GoTest::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .DATA_MANAGER_TABLE.TestType TestColumn = 2;
inline void GoTest::clear_testcolumn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testcolumn_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::DATA_MANAGER_TABLE::TestType GoTest::testcolumn() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.GoTest.TestColumn)
  return _internal_testcolumn();
}
inline void GoTest::set_testcolumn(::DATA_MANAGER_TABLE::TestType value) {
  _internal_set_testcolumn(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.GoTest.TestColumn)
}
inline ::DATA_MANAGER_TABLE::TestType GoTest::_internal_testcolumn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::DATA_MANAGER_TABLE::TestType>(_impl_.testcolumn_);
}
inline void GoTest::_internal_set_testcolumn(::DATA_MANAGER_TABLE::TestType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testcolumn_ = value;
}

// int32 Test23 = 3;
inline void GoTest::clear_test23() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.test23_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t GoTest::test23() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.GoTest.Test23)
  return _internal_test23();
}
inline void GoTest::set_test23(::int32_t value) {
  _internal_set_test23(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.GoTest.Test23)
}
inline ::int32_t GoTest::_internal_test23() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.test23_;
}
inline void GoTest::_internal_set_test23(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.test23_ = value;
}

// int32 Test45 = 4;
inline void GoTest::clear_test45() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.test45_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t GoTest::test45() const {
  // @@protoc_insertion_point(field_get:DATA_MANAGER_TABLE.GoTest.Test45)
  return _internal_test45();
}
inline void GoTest::set_test45(::int32_t value) {
  _internal_set_test45(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:DATA_MANAGER_TABLE.GoTest.Test45)
}
inline ::int32_t GoTest::_internal_test45() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.test45_;
}
inline void GoTest::_internal_set_test45(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.test45_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DATA_MANAGER_TABLE


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // TestTable_2eproto_2epb_2eh
