// Auto-generated by DataManager. DO NOT EDIT.
#include "DataTableLoader.h"
#include "Misc/Base64.h"

namespace
{
template <typename TEnum>
TEnum ParseEnumFromString(const FString& Value)
{
    const UEnum* Enum = StaticEnum<TEnum>();
    if (Enum)
    {
        const int64 Number = Enum->GetValueByNameString(Value);
        if (Number != INDEX_NONE) return static_cast<TEnum>(Number);
    }
    return static_cast<TEnum>(0);
}
} // namespace

void FCategory::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("parent"), Value)) { parent = MakeShared<FCategory>(); parent->ParseFromJson(*Value); } }
    {
        const TArray<TSharedPtr<FJsonValue>>* Array;
        if (Obj->TryGetArrayField(TEXT("children"), Array))
        {
            children.Reset();
            for (const TSharedPtr<FJsonValue>& Item : *Array) { const TSharedPtr<FJsonObject>* Object; if (Item->TryGetObject(Object)) { TSharedPtr<FCategory> Row = MakeShared<FCategory>(); Row->ParseFromJson(*Object); children.Add(Row); } }
        }
    }
}

void FCompositeTarget::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("region"), Value)) region = static_cast<int32>(Value); }
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    Obj->TryGetStringField(TEXT("label"), label);
}

void FCycleA::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("b"), Value)) { b = MakeShared<FCycleB>(); b->ParseFromJson(*Value); } }
}

void FCycleB::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("a"), Value)) { a = MakeShared<FCycleA>(); a->ParseFromJson(*Value); } }
}

void FGroupTarget::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("groupId"), Value)) groupId = static_cast<int32>(Value); }
    Obj->TryGetStringField(TEXT("label"), label);
}

void FSingleTarget::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    Obj->TryGetStringField(TEXT("label"), label);
    { FString Value; if (Obj->TryGetStringField(TEXT("state"), Value)) state = ParseEnumFromString<EFixtureState>(Value); }
}

void FMiddleTarget::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("single"), Value)) single.ParseFromJson(*Value); }
}

void FNoKeyTarget::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    Obj->TryGetStringField(TEXT("label"), label);
}

void FRootTarget::ParseFromJson(const TSharedPtr<FJsonObject>& Obj)
{
    { double Value = 0; if (Obj->TryGetNumberField(TEXT("id"), Value)) id = static_cast<int32>(Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("single"), Value)) single.ParseFromJson(*Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("composite"), Value)) composite.ParseFromJson(*Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("group"), Value)) group.ParseFromJson(*Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("middle"), Value)) middle.ParseFromJson(*Value); }
    { const TSharedPtr<FJsonObject>* Value; if (Obj->TryGetObjectField(TEXT("noKey"), Value)) noKey.ParseFromJson(*Value); }
    { FString Value; if (Obj->TryGetStringField(TEXT("state"), Value)) state = ParseEnumFromString<EFixtureState>(Value); }
}
