// Auto-generated by DataManager. DO NOT EDIT.
#pragma once

#include "CoreMinimal.h"
#include "DataTables.h"
#include "Misc/FileHelper.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"

struct FDataTableLoader
{
    template<typename T>
    static bool LoadFromJson(const FString& FilePath, TArray<T>& OutRows)
    {
        FString JsonString;
        if (!FFileHelper::LoadFileToString(JsonString, *FilePath)) return false;
        TArray<TSharedPtr<FJsonValue>> JsonArray;
        const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonString);
        if (!FJsonSerializer::Deserialize(Reader, JsonArray)) return false;
        OutRows.Reset();
        for (const TSharedPtr<FJsonValue>& Value : JsonArray)
        {
            const TSharedPtr<FJsonObject>* Object;
            if (!Value->TryGetObject(Object)) continue;
            T Row;
            Row.ParseFromJson(*Object);
            OutRows.Add(MoveTemp(Row));
        }
        return true;
    }
};
