// Auto-generated by DataManager. DO NOT EDIT.
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "FixtureEnumType.h"
#include "DataTables.generated.h"

class FJsonObject;

struct FCategory;
struct FCompositeTarget;
struct FCycleA;
struct FCycleB;
struct FGroupTarget;
struct FSingleTarget;
struct FMiddleTarget;
struct FNoKeyTarget;
struct FRootTarget;

USTRUCT(BlueprintType)
struct FCategory : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    // Cyclic references are not reflected as UPROPERTY values.
    TSharedPtr<FCategory> parent;

    // Cyclic references are not reflected as UPROPERTY values.
    TArray<TSharedPtr<FCategory>> children;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FCompositeTarget : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 region = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString label = TEXT("");

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FCycleA : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    // Cyclic references are not reflected as UPROPERTY values.
    TSharedPtr<FCycleB> b;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FCycleB : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    // Cyclic references are not reflected as UPROPERTY values.
    TSharedPtr<FCycleA> a;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FGroupTarget : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 groupId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString label = TEXT("");

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FSingleTarget : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString label = TEXT("");

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    EFixtureState state = static_cast<EFixtureState>(0);

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FMiddleTarget : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FSingleTarget single;

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FNoKeyTarget : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString label = TEXT("");

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};

USTRUCT(BlueprintType)
struct FRootTarget : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FSingleTarget single;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FCompositeTarget composite;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FGroupTarget group;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FMiddleTarget middle;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FNoKeyTarget noKey;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    EFixtureState state = static_cast<EFixtureState>(0);

    void ParseFromJson(const TSharedPtr<FJsonObject>& Obj);
};
