<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ReferenceTable.proto

namespace DATA_MANAGER_FIXTURE;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>DATA_MANAGER_FIXTURE.CycleB</code>
 */
class CycleB extends \Google\Protobuf\Internal\Message
{
    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.DATA_MANAGER_FIXTURE.CycleA a = 2;</code>
     */
    protected $a = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           \@PK
     *     @type \DATA_MANAGER_FIXTURE\CycleA $a
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ReferenceTable::initOnce();
        parent::__construct($data);
    }

    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DATA_MANAGER_FIXTURE.CycleA a = 2;</code>
     * @return \DATA_MANAGER_FIXTURE\CycleA|null
     */
    public function getA()
    {
        return $this->a;
    }

    public function hasA()
    {
        return isset($this->a);
    }

    public function clearA()
    {
        unset($this->a);
    }

    /**
     * Generated from protobuf field <code>.DATA_MANAGER_FIXTURE.CycleA a = 2;</code>
     * @param \DATA_MANAGER_FIXTURE\CycleA $var
     * @return $this
     */
    public function setA(\DATA_MANAGER_FIXTURE\CycleA|null $var)
    {
        $this->a = $var;

        return $this;
    }

}

