<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: KeyTable.proto

namespace DATA_MANAGER_FIXTURE;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>DATA_MANAGER_FIXTURE.SingleTarget</code>
 */
class SingleTarget extends \Google\Protobuf\Internal\Message
{
    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string label = 2;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>.DATA_MANAGER_FIXTURE.FixtureState state = 3;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           \@PK
     *     @type string $label
     *     @type int $state
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KeyTable::initOnce();
        parent::__construct($data);
    }

    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DATA_MANAGER_FIXTURE.FixtureState state = 3;</code>
     * @return int one of the values in {@see \DATA_MANAGER_FIXTURE\FixtureState}
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.DATA_MANAGER_FIXTURE.FixtureState state = 3;</code>
     * @param int $var one of the values in {@see \DATA_MANAGER_FIXTURE\FixtureState}
     * @return $this
     */
    public function setState(int $var)
    {
        GPBUtil::checkEnum($var, \DATA_MANAGER_FIXTURE\FixtureState::class);
        $this->state = $var;

        return $this;
    }

}

