// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameItemTable.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DATAMANAGERTABLE {

  /// <summary>Holder for reflection information generated from GameItemTable.proto</summary>
  public static partial class GameItemTableReflection {

    #region Descriptor
    /// <summary>File descriptor for GameItemTable.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameItemTableReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNHYW1lSXRlbVRhYmxlLnByb3RvEhJEQVRBX01BTkFHRVJfVEFCTEUaFENv",
            "bW1vbkVudW1UeXBlLnByb3RvGhJJdGVtRW51bVR5cGUucHJvdG8iewoRR2Ft",
            "ZUl0ZW1UeXBlVGFibGUSLgoIaXRlbVR5cGUYASABKA4yHC5EQVRBX01BTkFH",
            "RVJfVEFCTEUuSXRlbVR5cGUSEAoIdHlwZU5hbWUYAiABKAkSEgoKaXNUcmFk",
            "YWJsZRgDIAEoCBIQCghpY29uUGF0aBgEIAEoCSLHAQoIR2FtZUl0ZW0SDgoG",
            "aXRlbUlkGAEgASgFEgwKBG5hbWUYAiABKAkSNwoIaXRlbVR5cGUYAyABKAsy",
            "JS5EQVRBX01BTkFHRVJfVEFCTEUuR2FtZUl0ZW1UeXBlVGFibGUSLQoGcmFy",
            "aXR5GAQgASgOMh0uREFUQV9NQU5BR0VSX1RBQkxFLkdyYWRlVHlwZRIQCght",
            "YXhTdGFjaxgFIAEoBRINCgVwcmljZRgGIAEoBRIUCgxkZXNjcmlwdGlvbnMY",
            "ByABKAlCFloULi9EQVRBX01BTkFHRVJfVEFCTEViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DATAMANAGERTABLE.CommonEnumTypeReflection.Descriptor, global::DATAMANAGERTABLE.ItemEnumTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DATAMANAGERTABLE.GameItemTypeTable), global::DATAMANAGERTABLE.GameItemTypeTable.Parser, new[]{ "ItemType", "TypeName", "IsTradable", "IconPath" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DATAMANAGERTABLE.GameItem), global::DATAMANAGERTABLE.GameItem.Parser, new[]{ "ItemId", "Name", "ItemType", "Rarity", "MaxStack", "Price", "Descriptions" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameItemTypeTable : pb::IMessage<GameItemTypeTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameItemTypeTable> _parser = new pb::MessageParser<GameItemTypeTable>(() => new GameItemTypeTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameItemTypeTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DATAMANAGERTABLE.GameItemTableReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameItemTypeTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameItemTypeTable(GameItemTypeTable other) : this() {
      itemType_ = other.itemType_;
      typeName_ = other.typeName_;
      isTradable_ = other.isTradable_;
      iconPath_ = other.iconPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameItemTypeTable Clone() {
      return new GameItemTypeTable(this);
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 1;
    private global::DATAMANAGERTABLE.ItemType itemType_ = global::DATAMANAGERTABLE.ItemType.None;
    /// <summary>
    /// @PK
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DATAMANAGERTABLE.ItemType ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "typeName" field.</summary>
    public const int TypeNameFieldNumber = 2;
    private string typeName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TypeName {
      get { return typeName_; }
      set {
        typeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isTradable" field.</summary>
    public const int IsTradableFieldNumber = 3;
    private bool isTradable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsTradable {
      get { return isTradable_; }
      set {
        isTradable_ = value;
      }
    }

    /// <summary>Field number for the "iconPath" field.</summary>
    public const int IconPathFieldNumber = 4;
    private string iconPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IconPath {
      get { return iconPath_; }
      set {
        iconPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameItemTypeTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameItemTypeTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemType != other.ItemType) return false;
      if (TypeName != other.TypeName) return false;
      if (IsTradable != other.IsTradable) return false;
      if (IconPath != other.IconPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemType != global::DATAMANAGERTABLE.ItemType.None) hash ^= ItemType.GetHashCode();
      if (TypeName.Length != 0) hash ^= TypeName.GetHashCode();
      if (IsTradable != false) hash ^= IsTradable.GetHashCode();
      if (IconPath.Length != 0) hash ^= IconPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemType != global::DATAMANAGERTABLE.ItemType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ItemType);
      }
      if (TypeName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TypeName);
      }
      if (IsTradable != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsTradable);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IconPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemType != global::DATAMANAGERTABLE.ItemType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ItemType);
      }
      if (TypeName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TypeName);
      }
      if (IsTradable != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsTradable);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IconPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemType != global::DATAMANAGERTABLE.ItemType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
      }
      if (TypeName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TypeName);
      }
      if (IsTradable != false) {
        size += 1 + 1;
      }
      if (IconPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameItemTypeTable other) {
      if (other == null) {
        return;
      }
      if (other.ItemType != global::DATAMANAGERTABLE.ItemType.None) {
        ItemType = other.ItemType;
      }
      if (other.TypeName.Length != 0) {
        TypeName = other.TypeName;
      }
      if (other.IsTradable != false) {
        IsTradable = other.IsTradable;
      }
      if (other.IconPath.Length != 0) {
        IconPath = other.IconPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemType = (global::DATAMANAGERTABLE.ItemType) input.ReadEnum();
            break;
          }
          case 18: {
            TypeName = input.ReadString();
            break;
          }
          case 24: {
            IsTradable = input.ReadBool();
            break;
          }
          case 34: {
            IconPath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemType = (global::DATAMANAGERTABLE.ItemType) input.ReadEnum();
            break;
          }
          case 18: {
            TypeName = input.ReadString();
            break;
          }
          case 24: {
            IsTradable = input.ReadBool();
            break;
          }
          case 34: {
            IconPath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameItem : pb::IMessage<GameItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameItem> _parser = new pb::MessageParser<GameItem>(() => new GameItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DATAMANAGERTABLE.GameItemTableReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameItem(GameItem other) : this() {
      itemId_ = other.itemId_;
      name_ = other.name_;
      itemType_ = other.itemType_ != null ? other.itemType_.Clone() : null;
      rarity_ = other.rarity_;
      maxStack_ = other.maxStack_;
      price_ = other.price_;
      descriptions_ = other.descriptions_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameItem Clone() {
      return new GameItem(this);
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 1;
    private int itemId_;
    /// <summary>
    /// @PK
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 3;
    private global::DATAMANAGERTABLE.GameItemTypeTable itemType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DATAMANAGERTABLE.GameItemTypeTable ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "rarity" field.</summary>
    public const int RarityFieldNumber = 4;
    private global::DATAMANAGERTABLE.GradeType rarity_ = global::DATAMANAGERTABLE.GradeType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DATAMANAGERTABLE.GradeType Rarity {
      get { return rarity_; }
      set {
        rarity_ = value;
      }
    }

    /// <summary>Field number for the "maxStack" field.</summary>
    public const int MaxStackFieldNumber = 5;
    private int maxStack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxStack {
      get { return maxStack_; }
      set {
        maxStack_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 6;
    private int price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "descriptions" field.</summary>
    public const int DescriptionsFieldNumber = 7;
    private string descriptions_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Descriptions {
      get { return descriptions_; }
      set {
        descriptions_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemId != other.ItemId) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(ItemType, other.ItemType)) return false;
      if (Rarity != other.Rarity) return false;
      if (MaxStack != other.MaxStack) return false;
      if (Price != other.Price) return false;
      if (Descriptions != other.Descriptions) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemId != 0) hash ^= ItemId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (itemType_ != null) hash ^= ItemType.GetHashCode();
      if (Rarity != global::DATAMANAGERTABLE.GradeType.None) hash ^= Rarity.GetHashCode();
      if (MaxStack != 0) hash ^= MaxStack.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      if (Descriptions.Length != 0) hash ^= Descriptions.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (itemType_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ItemType);
      }
      if (Rarity != global::DATAMANAGERTABLE.GradeType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Rarity);
      }
      if (MaxStack != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxStack);
      }
      if (Price != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Price);
      }
      if (Descriptions.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Descriptions);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (itemType_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ItemType);
      }
      if (Rarity != global::DATAMANAGERTABLE.GradeType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Rarity);
      }
      if (MaxStack != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxStack);
      }
      if (Price != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Price);
      }
      if (Descriptions.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Descriptions);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (itemType_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemType);
      }
      if (Rarity != global::DATAMANAGERTABLE.GradeType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Rarity);
      }
      if (MaxStack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxStack);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      if (Descriptions.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Descriptions);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameItem other) {
      if (other == null) {
        return;
      }
      if (other.ItemId != 0) {
        ItemId = other.ItemId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.itemType_ != null) {
        if (itemType_ == null) {
          ItemType = new global::DATAMANAGERTABLE.GameItemTypeTable();
        }
        ItemType.MergeFrom(other.ItemType);
      }
      if (other.Rarity != global::DATAMANAGERTABLE.GradeType.None) {
        Rarity = other.Rarity;
      }
      if (other.MaxStack != 0) {
        MaxStack = other.MaxStack;
      }
      if (other.Price != 0) {
        Price = other.Price;
      }
      if (other.Descriptions.Length != 0) {
        Descriptions = other.Descriptions;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (itemType_ == null) {
              ItemType = new global::DATAMANAGERTABLE.GameItemTypeTable();
            }
            input.ReadMessage(ItemType);
            break;
          }
          case 32: {
            Rarity = (global::DATAMANAGERTABLE.GradeType) input.ReadEnum();
            break;
          }
          case 40: {
            MaxStack = input.ReadInt32();
            break;
          }
          case 48: {
            Price = input.ReadInt32();
            break;
          }
          case 58: {
            Descriptions = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (itemType_ == null) {
              ItemType = new global::DATAMANAGERTABLE.GameItemTypeTable();
            }
            input.ReadMessage(ItemType);
            break;
          }
          case 32: {
            Rarity = (global::DATAMANAGERTABLE.GradeType) input.ReadEnum();
            break;
          }
          case 40: {
            MaxStack = input.ReadInt32();
            break;
          }
          case 48: {
            Price = input.ReadInt32();
            break;
          }
          case 58: {
            Descriptions = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
