// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ItemEnumType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DATAMANAGERTABLE {

  /// <summary>Holder for reflection information generated from ItemEnumType.proto</summary>
  public static partial class ItemEnumTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemEnumType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemEnumTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJJdGVtRW51bVR5cGUucHJvdG8SEkRBVEFfTUFOQUdFUl9UQUJMRSqLAQoI",
            "SXRlbVR5cGUSEQoNSXRlbVR5cGVfTk9ORRAAEhYKEkl0ZW1UeXBlX0VRVUlQ",
            "TUVOVBABEhcKE0l0ZW1UeXBlX0NPTlNVTUFCTEUQAhIVChFJdGVtVHlwZV9N",
            "QVRFUklBTBADEhIKDkl0ZW1UeXBlX1FVRVNUEAQSEAoMSXRlbVR5cGVfTUFY",
            "EAVCFloULi9EQVRBX01BTkFHRVJfVEFCTEViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DATAMANAGERTABLE.ItemType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 아이템 종류 Enum
  /// </summary>
  public enum ItemType {
    [pbr::OriginalName("ItemType_NONE")] None = 0,
    [pbr::OriginalName("ItemType_EQUIPMENT")] Equipment = 1,
    [pbr::OriginalName("ItemType_CONSUMABLE")] Consumable = 2,
    [pbr::OriginalName("ItemType_MATERIAL")] Material = 3,
    [pbr::OriginalName("ItemType_QUEST")] Quest = 4,
    [pbr::OriginalName("ItemType_MAX")] Max = 5,
  }

  #endregion

}

#endregion Designer generated code
