// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestEnumType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DATAMANAGERTABLE {

  /// <summary>Holder for reflection information generated from TestEnumType.proto</summary>
  public static partial class TestEnumTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for TestEnumType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestEnumTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJUZXN0RW51bVR5cGUucHJvdG8SEkRBVEFfTUFOQUdFUl9UQUJMRSpXCghU",
            "ZXN0VHlwZRIRCg1UZXN0VHlwZV9OT05FEAASEgoOVGVzdFR5cGVfVGVzdDEQ",
            "ARISCg5UZXN0VHlwZV9UZXN0MhACEhAKDFRlc3RUeXBlX01BWBADKncKC0Jp",
            "Z1Rlc3RUeXBlEhQKEEJpZ1Rlc3RUeXBlX05PTkUQABIdChhCaWdUZXN0VHlw",
            "ZV9VbnJlYWwzMmJpdDEQ6AcSHQoYQmlnVGVzdFR5cGVfVW5yZWFsMzJiaXQy",
            "EOkHEhQKD0JpZ1Rlc3RUeXBlX01BWBDqB0IWWhQuL0RBVEFfTUFOQUdFUl9U",
            "QUJMRWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DATAMANAGERTABLE.TestType), typeof(global::DATAMANAGERTABLE.BigTestType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TestType {
    [pbr::OriginalName("TestType_NONE")] None = 0,
    [pbr::OriginalName("TestType_Test1")] Test1 = 1,
    [pbr::OriginalName("TestType_Test2")] Test2 = 2,
    [pbr::OriginalName("TestType_MAX")] Max = 3,
  }

  public enum BigTestType {
    [pbr::OriginalName("BigTestType_NONE")] None = 0,
    [pbr::OriginalName("BigTestType_Unreal32bit1")] Unreal32Bit1 = 1000,
    [pbr::OriginalName("BigTestType_Unreal32bit2")] Unreal32Bit2 = 1001,
    [pbr::OriginalName("BigTestType_MAX")] Max = 1002,
  }

  #endregion

}

#endregion Designer generated code
