<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CategoryTable.proto

namespace D1000;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>d1000.Category</code>
 */
class Category extends \Google\Protobuf\Internal\Message
{
    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>optional .d1000.Category parent = 2;</code>
     */
    protected $parent = null;
    /**
     * Generated from protobuf field <code>repeated .d1000.Category children = 3;</code>
     */
    private $children;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           \@PK
     *     @type \D1000\Category $parent
     *     @type \D1000\Category[] $children
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CategoryTable::initOnce();
        parent::__construct($data);
    }

    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * \@PK
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .d1000.Category parent = 2;</code>
     * @return \D1000\Category|null
     */
    public function getParent()
    {
        return $this->parent;
    }

    public function hasParent()
    {
        return isset($this->parent);
    }

    public function clearParent()
    {
        unset($this->parent);
    }

    /**
     * Generated from protobuf field <code>optional .d1000.Category parent = 2;</code>
     * @param \D1000\Category $var
     * @return $this
     */
    public function setParent(\D1000\Category|null $var)
    {
        $this->parent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .d1000.Category children = 3;</code>
     * @return RepeatedField<\D1000\Category>
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Generated from protobuf field <code>repeated .d1000.Category children = 3;</code>
     * @param \D1000\Category[] $var
     * @return $this
     */
    public function setChildren(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \D1000\Category::class);
        $this->children = $arr;

        return $this;
    }

}

