// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: CommonEnumType.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GradeType int32

const (
	GradeType_GradeType_NONE      GradeType = 0
	GradeType_GradeType_NORMAL    GradeType = 1
	GradeType_GradeType_SUPERIOR  GradeType = 2
	GradeType_GradeType_RARE      GradeType = 3
	GradeType_GradeType_EPIC      GradeType = 4
	GradeType_GradeType_LEGENDARY GradeType = 5
	GradeType_GradeType_MAX       GradeType = 6
)

// Enum value maps for GradeType.
var (
	GradeType_name = map[int32]string{
		0: "GradeType_NONE",
		1: "GradeType_NORMAL",
		2: "GradeType_SUPERIOR",
		3: "GradeType_RARE",
		4: "GradeType_EPIC",
		5: "GradeType_LEGENDARY",
		6: "GradeType_MAX",
	}
	GradeType_value = map[string]int32{
		"GradeType_NONE":      0,
		"GradeType_NORMAL":    1,
		"GradeType_SUPERIOR":  2,
		"GradeType_RARE":      3,
		"GradeType_EPIC":      4,
		"GradeType_LEGENDARY": 5,
		"GradeType_MAX":       6,
	}
)

func (x GradeType) Enum() *GradeType {
	p := new(GradeType)
	*p = x
	return p
}

func (x GradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonEnumType_proto_enumTypes[0].Descriptor()
}

func (GradeType) Type() protoreflect.EnumType {
	return &file_CommonEnumType_proto_enumTypes[0]
}

func (x GradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GradeType.Descriptor instead.
func (GradeType) EnumDescriptor() ([]byte, []int) {
	return file_CommonEnumType_proto_rawDescGZIP(), []int{0}
}

var File_CommonEnumType_proto protoreflect.FileDescriptor

var file_CommonEnumType_proto_rawDesc = []byte{
	0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e,
	0x41, 0x47, 0x45, 0x52, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x2a, 0xa1, 0x01, 0x0a, 0x09, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c,
	0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x53, 0x55, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x52, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12, 0x12,
	0x0a, 0x0e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x45, 0x50, 0x49, 0x43,
	0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x4c, 0x45, 0x47, 0x45, 0x4e, 0x44, 0x41, 0x52, 0x59, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x41, 0x58, 0x10, 0x06, 0x42, 0x16,
	0x5a, 0x14, 0x2e, 0x2f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52,
	0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonEnumType_proto_rawDescOnce sync.Once
	file_CommonEnumType_proto_rawDescData = file_CommonEnumType_proto_rawDesc
)

func file_CommonEnumType_proto_rawDescGZIP() []byte {
	file_CommonEnumType_proto_rawDescOnce.Do(func() {
		file_CommonEnumType_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonEnumType_proto_rawDescData)
	})
	return file_CommonEnumType_proto_rawDescData
}

var file_CommonEnumType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonEnumType_proto_goTypes = []interface{}{
	(GradeType)(0), // 0: DATA_MANAGER_TABLE.GradeType
}
var file_CommonEnumType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CommonEnumType_proto_init() }
func file_CommonEnumType_proto_init() {
	if File_CommonEnumType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonEnumType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonEnumType_proto_goTypes,
		DependencyIndexes: file_CommonEnumType_proto_depIdxs,
		EnumInfos:         file_CommonEnumType_proto_enumTypes,
	}.Build()
	File_CommonEnumType_proto = out.File
	file_CommonEnumType_proto_rawDesc = nil
	file_CommonEnumType_proto_goTypes = nil
	file_CommonEnumType_proto_depIdxs = nil
}
