// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: GameItemTable.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameItemTypeTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	ItemType      ItemType `protobuf:"varint,1,opt,name=itemType,proto3,enum=DATA_MANAGER_TABLE.ItemType" json:"itemType,omitempty"`
	TypeName      string   `protobuf:"bytes,2,opt,name=typeName,proto3" json:"typeName,omitempty"`
	IsTradable    bool     `protobuf:"varint,3,opt,name=isTradable,proto3" json:"isTradable,omitempty"`
	IconPath      string   `protobuf:"bytes,4,opt,name=iconPath,proto3" json:"iconPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameItemTypeTable) Reset() {
	*x = GameItemTypeTable{}
	mi := &file_GameItemTable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameItemTypeTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameItemTypeTable) ProtoMessage() {}

func (x *GameItemTypeTable) ProtoReflect() protoreflect.Message {
	mi := &file_GameItemTable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameItemTypeTable.ProtoReflect.Descriptor instead.
func (*GameItemTypeTable) Descriptor() ([]byte, []int) {
	return file_GameItemTable_proto_rawDescGZIP(), []int{0}
}

func (x *GameItemTypeTable) GetItemType() ItemType {
	if x != nil {
		return x.ItemType
	}
	return ItemType_ItemType_NONE
}

func (x *GameItemTypeTable) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *GameItemTypeTable) GetIsTradable() bool {
	if x != nil {
		return x.IsTradable
	}
	return false
}

func (x *GameItemTypeTable) GetIconPath() string {
	if x != nil {
		return x.IconPath
	}
	return ""
}

type GameItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	ItemId        int32              `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Name          string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ItemType      *GameItemTypeTable `protobuf:"bytes,3,opt,name=itemType,proto3" json:"itemType,omitempty"`
	Rarity        GradeType          `protobuf:"varint,4,opt,name=rarity,proto3,enum=DATA_MANAGER_TABLE.GradeType" json:"rarity,omitempty"`
	MaxStack      int32              `protobuf:"varint,5,opt,name=maxStack,proto3" json:"maxStack,omitempty"`
	Price         int32              `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Descriptions  string             `protobuf:"bytes,7,opt,name=descriptions,proto3" json:"descriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameItem) Reset() {
	*x = GameItem{}
	mi := &file_GameItemTable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameItem) ProtoMessage() {}

func (x *GameItem) ProtoReflect() protoreflect.Message {
	mi := &file_GameItemTable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameItem.ProtoReflect.Descriptor instead.
func (*GameItem) Descriptor() ([]byte, []int) {
	return file_GameItemTable_proto_rawDescGZIP(), []int{1}
}

func (x *GameItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GameItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameItem) GetItemType() *GameItemTypeTable {
	if x != nil {
		return x.ItemType
	}
	return nil
}

func (x *GameItem) GetRarity() GradeType {
	if x != nil {
		return x.Rarity
	}
	return GradeType_GradeType_NONE
}

func (x *GameItem) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *GameItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GameItem) GetDescriptions() string {
	if x != nil {
		return x.Descriptions
	}
	return ""
}

var File_GameItemTable_proto protoreflect.FileDescriptor

const file_GameItemTable_proto_rawDesc = "" +
	"\n" +
	"\x13GameItemTable.proto\x12\x12DATA_MANAGER_TABLE\x1a\x14CommonEnumType.proto\x1a\x12ItemEnumType.proto\"\xa5\x01\n" +
	"\x11GameItemTypeTable\x128\n" +
	"\bitemType\x18\x01 \x01(\x0e2\x1c.DATA_MANAGER_TABLE.ItemTypeR\bitemType\x12\x1a\n" +
	"\btypeName\x18\x02 \x01(\tR\btypeName\x12\x1e\n" +
	"\n" +
	"isTradable\x18\x03 \x01(\bR\n" +
	"isTradable\x12\x1a\n" +
	"\biconPath\x18\x04 \x01(\tR\biconPath\"\x86\x02\n" +
	"\bGameItem\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\bitemType\x18\x03 \x01(\v2%.DATA_MANAGER_TABLE.GameItemTypeTableR\bitemType\x125\n" +
	"\x06rarity\x18\x04 \x01(\x0e2\x1d.DATA_MANAGER_TABLE.GradeTypeR\x06rarity\x12\x1a\n" +
	"\bmaxStack\x18\x05 \x01(\x05R\bmaxStack\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12\"\n" +
	"\fdescriptions\x18\a \x01(\tR\fdescriptionsB\x16Z\x14./DATA_MANAGER_TABLEb\x06proto3"

var (
	file_GameItemTable_proto_rawDescOnce sync.Once
	file_GameItemTable_proto_rawDescData []byte
)

func file_GameItemTable_proto_rawDescGZIP() []byte {
	file_GameItemTable_proto_rawDescOnce.Do(func() {
		file_GameItemTable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GameItemTable_proto_rawDesc), len(file_GameItemTable_proto_rawDesc)))
	})
	return file_GameItemTable_proto_rawDescData
}

var file_GameItemTable_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GameItemTable_proto_goTypes = []any{
	(*GameItemTypeTable)(nil), // 0: DATA_MANAGER_TABLE.GameItemTypeTable
	(*GameItem)(nil),          // 1: DATA_MANAGER_TABLE.GameItem
	(ItemType)(0),             // 2: DATA_MANAGER_TABLE.ItemType
	(GradeType)(0),            // 3: DATA_MANAGER_TABLE.GradeType
}
var file_GameItemTable_proto_depIdxs = []int32{
	2, // 0: DATA_MANAGER_TABLE.GameItemTypeTable.itemType:type_name -> DATA_MANAGER_TABLE.ItemType
	0, // 1: DATA_MANAGER_TABLE.GameItem.itemType:type_name -> DATA_MANAGER_TABLE.GameItemTypeTable
	3, // 2: DATA_MANAGER_TABLE.GameItem.rarity:type_name -> DATA_MANAGER_TABLE.GradeType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GameItemTable_proto_init() }
func file_GameItemTable_proto_init() {
	if File_GameItemTable_proto != nil {
		return
	}
	file_CommonEnumType_proto_init()
	file_ItemEnumType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GameItemTable_proto_rawDesc), len(file_GameItemTable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameItemTable_proto_goTypes,
		DependencyIndexes: file_GameItemTable_proto_depIdxs,
		MessageInfos:      file_GameItemTable_proto_msgTypes,
	}.Build()
	File_GameItemTable_proto = out.File
	file_GameItemTable_proto_goTypes = nil
	file_GameItemTable_proto_depIdxs = nil
}
