// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: ItemEnumType.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 아이템 종류 Enum
type ItemType int32

const (
	ItemType_ItemType_NONE       ItemType = 0
	ItemType_ItemType_EQUIPMENT  ItemType = 1
	ItemType_ItemType_CONSUMABLE ItemType = 2
	ItemType_ItemType_MATERIAL   ItemType = 3
	ItemType_ItemType_QUEST      ItemType = 4
	ItemType_ItemType_MAX        ItemType = 5
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ItemType_NONE",
		1: "ItemType_EQUIPMENT",
		2: "ItemType_CONSUMABLE",
		3: "ItemType_MATERIAL",
		4: "ItemType_QUEST",
		5: "ItemType_MAX",
	}
	ItemType_value = map[string]int32{
		"ItemType_NONE":       0,
		"ItemType_EQUIPMENT":  1,
		"ItemType_CONSUMABLE": 2,
		"ItemType_MATERIAL":   3,
		"ItemType_QUEST":      4,
		"ItemType_MAX":        5,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_ItemEnumType_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_ItemEnumType_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_ItemEnumType_proto_rawDescGZIP(), []int{0}
}

var File_ItemEnumType_proto protoreflect.FileDescriptor

var file_ItemEnumType_proto_rawDesc = []byte{
	0x0a, 0x12, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47,
	0x45, 0x52, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x2a, 0x8b, 0x01, 0x0a, 0x08, 0x49, 0x74, 0x65,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x4f, 0x4e,
	0x53, 0x55, 0x4d, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x74, 0x65,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x41, 0x54, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x4d, 0x41, 0x58, 0x10, 0x05, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x44, 0x41, 0x54, 0x41,
	0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ItemEnumType_proto_rawDescOnce sync.Once
	file_ItemEnumType_proto_rawDescData = file_ItemEnumType_proto_rawDesc
)

func file_ItemEnumType_proto_rawDescGZIP() []byte {
	file_ItemEnumType_proto_rawDescOnce.Do(func() {
		file_ItemEnumType_proto_rawDescData = protoimpl.X.CompressGZIP(file_ItemEnumType_proto_rawDescData)
	})
	return file_ItemEnumType_proto_rawDescData
}

var file_ItemEnumType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ItemEnumType_proto_goTypes = []interface{}{
	(ItemType)(0), // 0: DATA_MANAGER_TABLE.ItemType
}
var file_ItemEnumType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ItemEnumType_proto_init() }
func file_ItemEnumType_proto_init() {
	if File_ItemEnumType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ItemEnumType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ItemEnumType_proto_goTypes,
		DependencyIndexes: file_ItemEnumType_proto_depIdxs,
		EnumInfos:         file_ItemEnumType_proto_enumTypes,
	}.Build()
	File_ItemEnumType_proto = out.File
	file_ItemEnumType_proto_rawDesc = nil
	file_ItemEnumType_proto_goTypes = nil
	file_ItemEnumType_proto_depIdxs = nil
}
