// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: MonsterTable.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonsterRace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	GroupID int32 `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	// @PK
	MonsterID *Monster `protobuf:"bytes,2,opt,name=MonsterID,proto3" json:"MonsterID,omitempty"`
}

func (x *MonsterRace) Reset() {
	*x = MonsterRace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MonsterTable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonsterRace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterRace) ProtoMessage() {}

func (x *MonsterRace) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterRace.ProtoReflect.Descriptor instead.
func (*MonsterRace) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{0}
}

func (x *MonsterRace) GetGroupID() int32 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *MonsterRace) GetMonsterID() *Monster {
	if x != nil {
		return x.MonsterID
	}
	return nil
}

type Monster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @PK
	MonsterId     int32            `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Name          *StringData      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32            `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	Atk           int32            `protobuf:"varint,4,opt,name=atk,proto3" json:"atk,omitempty"`
	Def           int32            `protobuf:"varint,5,opt,name=def,proto3" json:"def,omitempty"`
	MoveSpeed     float32          `protobuf:"fixed32,6,opt,name=moveSpeed,proto3" json:"moveSpeed,omitempty"`
	RewardGroupId *RewardItemGroup `protobuf:"bytes,7,opt,name=RewardGroupId,proto3" json:"RewardGroupId,omitempty"`
}

func (x *Monster) Reset() {
	*x = Monster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MonsterTable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{1}
}

func (x *Monster) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *Monster) GetName() *StringData {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Monster) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Monster) GetAtk() int32 {
	if x != nil {
		return x.Atk
	}
	return 0
}

func (x *Monster) GetDef() int32 {
	if x != nil {
		return x.Def
	}
	return 0
}

func (x *Monster) GetMoveSpeed() float32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *Monster) GetRewardGroupId() *RewardItemGroup {
	if x != nil {
		return x.RewardGroupId
	}
	return nil
}

var File_MonsterTable_proto protoreflect.FileDescriptor

var file_MonsterTable_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47,
	0x45, 0x52, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x1a, 0x15, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0b, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x61, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x39, 0x0a, 0x09, 0x4d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x09, 0x4d, 0x6f, 0x6e,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22, 0xf8, 0x01, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x68, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x74, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x74, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x66, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x65, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x49, 0x0a, 0x0d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x54, 0x41, 0x42,
	0x4c, 0x45, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x0d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x41, 0x4e, 0x41,
	0x47, 0x45, 0x52, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_MonsterTable_proto_rawDescOnce sync.Once
	file_MonsterTable_proto_rawDescData = file_MonsterTable_proto_rawDesc
)

func file_MonsterTable_proto_rawDescGZIP() []byte {
	file_MonsterTable_proto_rawDescOnce.Do(func() {
		file_MonsterTable_proto_rawDescData = protoimpl.X.CompressGZIP(file_MonsterTable_proto_rawDescData)
	})
	return file_MonsterTable_proto_rawDescData
}

var file_MonsterTable_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_MonsterTable_proto_goTypes = []interface{}{
	(*MonsterRace)(nil),     // 0: DATA_MANAGER_TABLE.MonsterRace
	(*Monster)(nil),         // 1: DATA_MANAGER_TABLE.Monster
	(*StringData)(nil),      // 2: DATA_MANAGER_TABLE.StringData
	(*RewardItemGroup)(nil), // 3: DATA_MANAGER_TABLE.RewardItemGroup
}
var file_MonsterTable_proto_depIdxs = []int32{
	1, // 0: DATA_MANAGER_TABLE.MonsterRace.MonsterID:type_name -> DATA_MANAGER_TABLE.Monster
	2, // 1: DATA_MANAGER_TABLE.Monster.name:type_name -> DATA_MANAGER_TABLE.StringData
	3, // 2: DATA_MANAGER_TABLE.Monster.RewardGroupId:type_name -> DATA_MANAGER_TABLE.RewardItemGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_MonsterTable_proto_init() }
func file_MonsterTable_proto_init() {
	if File_MonsterTable_proto != nil {
		return
	}
	file_RewardItemTable_proto_init()
	file_StringTable_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_MonsterTable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonsterRace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MonsterTable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MonsterTable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MonsterTable_proto_goTypes,
		DependencyIndexes: file_MonsterTable_proto_depIdxs,
		MessageInfos:      file_MonsterTable_proto_msgTypes,
	}.Build()
	File_MonsterTable_proto = out.File
	file_MonsterTable_proto_rawDesc = nil
	file_MonsterTable_proto_goTypes = nil
	file_MonsterTable_proto_depIdxs = nil
}
