// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: MonsterTable.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonsterRace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	GroupID int32 `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	// @PK
	MonsterID     *Monster `protobuf:"bytes,2,opt,name=MonsterID,proto3" json:"MonsterID,omitempty"`
	Memo          int32    `protobuf:"varint,3,opt,name=Memo,proto3" json:"Memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterRace) Reset() {
	*x = MonsterRace{}
	mi := &file_MonsterTable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterRace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterRace) ProtoMessage() {}

func (x *MonsterRace) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterRace.ProtoReflect.Descriptor instead.
func (*MonsterRace) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{0}
}

func (x *MonsterRace) GetGroupID() int32 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *MonsterRace) GetMonsterID() *Monster {
	if x != nil {
		return x.MonsterID
	}
	return nil
}

func (x *MonsterRace) GetMemo() int32 {
	if x != nil {
		return x.Memo
	}
	return 0
}

type Monster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	MonsterId     int32            `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Name          *StringData      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32            `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	Atk           int32            `protobuf:"varint,4,opt,name=atk,proto3" json:"atk,omitempty"`
	Def           int32            `protobuf:"varint,5,opt,name=def,proto3" json:"def,omitempty"`
	MoveSpeed     float32          `protobuf:"fixed32,6,opt,name=moveSpeed,proto3" json:"moveSpeed,omitempty"`
	RewardGroupId *RewardItemGroup `protobuf:"bytes,7,opt,name=RewardGroupId,proto3" json:"RewardGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monster) Reset() {
	*x = Monster{}
	mi := &file_MonsterTable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{1}
}

func (x *Monster) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *Monster) GetName() *StringData {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Monster) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Monster) GetAtk() int32 {
	if x != nil {
		return x.Atk
	}
	return 0
}

func (x *Monster) GetDef() int32 {
	if x != nil {
		return x.Def
	}
	return 0
}

func (x *Monster) GetMoveSpeed() float32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *Monster) GetRewardGroupId() *RewardItemGroup {
	if x != nil {
		return x.RewardGroupId
	}
	return nil
}

var File_MonsterTable_proto protoreflect.FileDescriptor

const file_MonsterTable_proto_rawDesc = "" +
	"\n" +
	"\x12MonsterTable.proto\x12\x12DATA_MANAGER_TABLE\x1a\x15RewardItemTable.proto\x1a\x11StringTable.proto\"v\n" +
	"\vMonsterRace\x12\x18\n" +
	"\aGroupID\x18\x01 \x01(\x05R\aGroupID\x129\n" +
	"\tMonsterID\x18\x02 \x01(\v2\x1b.DATA_MANAGER_TABLE.MonsterR\tMonsterID\x12\x12\n" +
	"\x04Memo\x18\x03 \x01(\x05R\x04Memo\"\xf8\x01\n" +
	"\aMonster\x12\x1c\n" +
	"\tmonsterId\x18\x01 \x01(\x05R\tmonsterId\x122\n" +
	"\x04name\x18\x02 \x01(\v2\x1e.DATA_MANAGER_TABLE.StringDataR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x10\n" +
	"\x03atk\x18\x04 \x01(\x05R\x03atk\x12\x10\n" +
	"\x03def\x18\x05 \x01(\x05R\x03def\x12\x1c\n" +
	"\tmoveSpeed\x18\x06 \x01(\x02R\tmoveSpeed\x12I\n" +
	"\rRewardGroupId\x18\a \x01(\v2#.DATA_MANAGER_TABLE.RewardItemGroupR\rRewardGroupIdB\x16Z\x14./DATA_MANAGER_TABLEb\x06proto3"

var (
	file_MonsterTable_proto_rawDescOnce sync.Once
	file_MonsterTable_proto_rawDescData []byte
)

func file_MonsterTable_proto_rawDescGZIP() []byte {
	file_MonsterTable_proto_rawDescOnce.Do(func() {
		file_MonsterTable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MonsterTable_proto_rawDesc), len(file_MonsterTable_proto_rawDesc)))
	})
	return file_MonsterTable_proto_rawDescData
}

var file_MonsterTable_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_MonsterTable_proto_goTypes = []any{
	(*MonsterRace)(nil),     // 0: DATA_MANAGER_TABLE.MonsterRace
	(*Monster)(nil),         // 1: DATA_MANAGER_TABLE.Monster
	(*StringData)(nil),      // 2: DATA_MANAGER_TABLE.StringData
	(*RewardItemGroup)(nil), // 3: DATA_MANAGER_TABLE.RewardItemGroup
}
var file_MonsterTable_proto_depIdxs = []int32{
	1, // 0: DATA_MANAGER_TABLE.MonsterRace.MonsterID:type_name -> DATA_MANAGER_TABLE.Monster
	2, // 1: DATA_MANAGER_TABLE.Monster.name:type_name -> DATA_MANAGER_TABLE.StringData
	3, // 2: DATA_MANAGER_TABLE.Monster.RewardGroupId:type_name -> DATA_MANAGER_TABLE.RewardItemGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_MonsterTable_proto_init() }
func file_MonsterTable_proto_init() {
	if File_MonsterTable_proto != nil {
		return
	}
	file_RewardItemTable_proto_init()
	file_StringTable_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MonsterTable_proto_rawDesc), len(file_MonsterTable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MonsterTable_proto_goTypes,
		DependencyIndexes: file_MonsterTable_proto_depIdxs,
		MessageInfos:      file_MonsterTable_proto_msgTypes,
	}.Build()
	File_MonsterTable_proto = out.File
	file_MonsterTable_proto_goTypes = nil
	file_MonsterTable_proto_depIdxs = nil
}
