// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: MonsterTable.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonsterTest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	ID            int32        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MonsterDrop   *MonsterDrop `protobuf:"bytes,2,opt,name=MonsterDrop,proto3" json:"MonsterDrop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterTest) Reset() {
	*x = MonsterTest{}
	mi := &file_MonsterTable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterTest) ProtoMessage() {}

func (x *MonsterTest) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterTest.ProtoReflect.Descriptor instead.
func (*MonsterTest) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{0}
}

func (x *MonsterTest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MonsterTest) GetMonsterDrop() *MonsterDrop {
	if x != nil {
		return x.MonsterDrop
	}
	return nil
}

type Monster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	MonsterId     int32   `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32   `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	Atk           int32   `protobuf:"varint,4,opt,name=atk,proto3" json:"atk,omitempty"`
	Def           int32   `protobuf:"varint,5,opt,name=def,proto3" json:"def,omitempty"`
	MoveSpeed     float32 `protobuf:"fixed32,6,opt,name=moveSpeed,proto3" json:"moveSpeed,omitempty"`
	RewardItemId  int32   `protobuf:"varint,7,opt,name=rewardItemId,proto3" json:"rewardItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monster) Reset() {
	*x = Monster{}
	mi := &file_MonsterTable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{1}
}

func (x *Monster) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *Monster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Monster) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Monster) GetAtk() int32 {
	if x != nil {
		return x.Atk
	}
	return 0
}

func (x *Monster) GetDef() int32 {
	if x != nil {
		return x.Def
	}
	return 0
}

func (x *Monster) GetMoveSpeed() float32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *Monster) GetRewardItemId() int32 {
	if x != nil {
		return x.RewardItemId
	}
	return 0
}

type MonsterDrop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @PK
	MonsterId *MonsterDrop `protobuf:"bytes,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	// @PK
	ItemId        int32   `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	DropRate      float32 `protobuf:"fixed32,3,opt,name=dropRate,proto3" json:"dropRate,omitempty"`
	MinCount      int32   `protobuf:"varint,4,opt,name=minCount,proto3" json:"minCount,omitempty"`
	MaxCount      int32   `protobuf:"varint,5,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterDrop) Reset() {
	*x = MonsterDrop{}
	mi := &file_MonsterTable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterDrop) ProtoMessage() {}

func (x *MonsterDrop) ProtoReflect() protoreflect.Message {
	mi := &file_MonsterTable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterDrop.ProtoReflect.Descriptor instead.
func (*MonsterDrop) Descriptor() ([]byte, []int) {
	return file_MonsterTable_proto_rawDescGZIP(), []int{2}
}

func (x *MonsterDrop) GetMonsterId() *MonsterDrop {
	if x != nil {
		return x.MonsterId
	}
	return nil
}

func (x *MonsterDrop) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MonsterDrop) GetDropRate() float32 {
	if x != nil {
		return x.DropRate
	}
	return 0
}

func (x *MonsterDrop) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

func (x *MonsterDrop) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

var File_MonsterTable_proto protoreflect.FileDescriptor

const file_MonsterTable_proto_rawDesc = "" +
	"\n" +
	"\x12MonsterTable.proto\x12\x12DATA_MANAGER_TABLE\"`\n" +
	"\vMonsterTest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12A\n" +
	"\vMonsterDrop\x18\x02 \x01(\v2\x1f.DATA_MANAGER_TABLE.MonsterDropR\vMonsterDrop\"\xb1\x01\n" +
	"\aMonster\x12\x1c\n" +
	"\tmonsterId\x18\x01 \x01(\x05R\tmonsterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x10\n" +
	"\x03atk\x18\x04 \x01(\x05R\x03atk\x12\x10\n" +
	"\x03def\x18\x05 \x01(\x05R\x03def\x12\x1c\n" +
	"\tmoveSpeed\x18\x06 \x01(\x02R\tmoveSpeed\x12\"\n" +
	"\frewardItemId\x18\a \x01(\x05R\frewardItemId\"\xb8\x01\n" +
	"\vMonsterDrop\x12=\n" +
	"\tmonsterId\x18\x01 \x01(\v2\x1f.DATA_MANAGER_TABLE.MonsterDropR\tmonsterId\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\x05R\x06itemId\x12\x1a\n" +
	"\bdropRate\x18\x03 \x01(\x02R\bdropRate\x12\x1a\n" +
	"\bminCount\x18\x04 \x01(\x05R\bminCount\x12\x1a\n" +
	"\bmaxCount\x18\x05 \x01(\x05R\bmaxCountB\x16Z\x14./DATA_MANAGER_TABLEb\x06proto3"

var (
	file_MonsterTable_proto_rawDescOnce sync.Once
	file_MonsterTable_proto_rawDescData []byte
)

func file_MonsterTable_proto_rawDescGZIP() []byte {
	file_MonsterTable_proto_rawDescOnce.Do(func() {
		file_MonsterTable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MonsterTable_proto_rawDesc), len(file_MonsterTable_proto_rawDesc)))
	})
	return file_MonsterTable_proto_rawDescData
}

var file_MonsterTable_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_MonsterTable_proto_goTypes = []any{
	(*MonsterTest)(nil), // 0: DATA_MANAGER_TABLE.MonsterTest
	(*Monster)(nil),     // 1: DATA_MANAGER_TABLE.Monster
	(*MonsterDrop)(nil), // 2: DATA_MANAGER_TABLE.MonsterDrop
}
var file_MonsterTable_proto_depIdxs = []int32{
	2, // 0: DATA_MANAGER_TABLE.MonsterTest.MonsterDrop:type_name -> DATA_MANAGER_TABLE.MonsterDrop
	2, // 1: DATA_MANAGER_TABLE.MonsterDrop.monsterId:type_name -> DATA_MANAGER_TABLE.MonsterDrop
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_MonsterTable_proto_init() }
func file_MonsterTable_proto_init() {
	if File_MonsterTable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MonsterTable_proto_rawDesc), len(file_MonsterTable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MonsterTable_proto_goTypes,
		DependencyIndexes: file_MonsterTable_proto_depIdxs,
		MessageInfos:      file_MonsterTable_proto_msgTypes,
	}.Build()
	File_MonsterTable_proto = out.File
	file_MonsterTable_proto_goTypes = nil
	file_MonsterTable_proto_depIdxs = nil
}
