// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: TestEnumType.proto

package DATA_MANAGER_TABLE

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestType int32

const (
	TestType_TestType_NONE  TestType = 0
	TestType_TestType_Test1 TestType = 1
	TestType_TestType_Test2 TestType = 2
	TestType_TestType_MAX   TestType = 3
)

// Enum value maps for TestType.
var (
	TestType_name = map[int32]string{
		0: "TestType_NONE",
		1: "TestType_Test1",
		2: "TestType_Test2",
		3: "TestType_MAX",
	}
	TestType_value = map[string]int32{
		"TestType_NONE":  0,
		"TestType_Test1": 1,
		"TestType_Test2": 2,
		"TestType_MAX":   3,
	}
)

func (x TestType) Enum() *TestType {
	p := new(TestType)
	*p = x
	return p
}

func (x TestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestType) Descriptor() protoreflect.EnumDescriptor {
	return file_TestEnumType_proto_enumTypes[0].Descriptor()
}

func (TestType) Type() protoreflect.EnumType {
	return &file_TestEnumType_proto_enumTypes[0]
}

func (x TestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestType.Descriptor instead.
func (TestType) EnumDescriptor() ([]byte, []int) {
	return file_TestEnumType_proto_rawDescGZIP(), []int{0}
}

var File_TestEnumType_proto protoreflect.FileDescriptor

const file_TestEnumType_proto_rawDesc = "" +
	"\n" +
	"\x12TestEnumType.proto\x12\x12DATA_MANAGER_TABLE*W\n" +
	"\bTestType\x12\x11\n" +
	"\rTestType_NONE\x10\x00\x12\x12\n" +
	"\x0eTestType_Test1\x10\x01\x12\x12\n" +
	"\x0eTestType_Test2\x10\x02\x12\x10\n" +
	"\fTestType_MAX\x10\x03B\x16Z\x14./DATA_MANAGER_TABLEb\x06proto3"

var (
	file_TestEnumType_proto_rawDescOnce sync.Once
	file_TestEnumType_proto_rawDescData []byte
)

func file_TestEnumType_proto_rawDescGZIP() []byte {
	file_TestEnumType_proto_rawDescOnce.Do(func() {
		file_TestEnumType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TestEnumType_proto_rawDesc), len(file_TestEnumType_proto_rawDesc)))
	})
	return file_TestEnumType_proto_rawDescData
}

var file_TestEnumType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TestEnumType_proto_goTypes = []any{
	(TestType)(0), // 0: DATA_MANAGER_TABLE.TestType
}
var file_TestEnumType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TestEnumType_proto_init() }
func file_TestEnumType_proto_init() {
	if File_TestEnumType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TestEnumType_proto_rawDesc), len(file_TestEnumType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TestEnumType_proto_goTypes,
		DependencyIndexes: file_TestEnumType_proto_depIdxs,
		EnumInfos:         file_TestEnumType_proto_enumTypes,
	}.Build()
	File_TestEnumType_proto = out.File
	file_TestEnumType_proto_goTypes = nil
	file_TestEnumType_proto_depIdxs = nil
}
